### ISSUE TITLE
Weird BellyDesc error

### ISSUE THREAD

**Issue by megas4o** [Free-Cities/Free-Cities#1004]
This Slave is throwing a weird widget error, which I wasn't able to backtrace. Doesn't affect other slaves and doesn't change even after manipulating the slave in all kinds of ways.

[free-cities-20170826-114741.zip](https://github.com/Free-Cities/Free-Cities/files/1253532/free-cities-20170826-114741.zip)
![screenshot](https://user-images.githubusercontent.com/22507519/29740008-2f7af970-8a55-11e7-8b85-abc0c5c8ae06.jpg)

**Comment by pregAnon** [comment]
If I'm remembering right, it should be a bad .includes in "a leotard", I think.

**Comment by megas4o** [comment]
Changed another slave's outfit to a leotard,impregnated her and put on a fake belly,just as this one and it didn't error out.

**Comment by pregAnon** [comment]
Will try to figure it out. Might as well get the other bugs too while I'm at it.
