### ISSUE TITLE
How do you "none"?

### ISSUE THREAD

**Issue by megas4o** [Free-Cities/Free-Cities#1005]
After the last RA changes this happens
![none](https://user-images.githubusercontent.com/22507519/29740329-8e417176-8a5c-11e7-8744-ac9906e2894c.jpg)
![none2](https://user-images.githubusercontent.com/22507519/29740328-8e3b2f1e-8a5c-11e7-81da-61e01d5d5f87.jpg)

If someone can explain how a person does "none" I will be very grateful

**Comment by pregAnon** [comment]
Backwards compatibility fixes it, but the default rules and whatnot need to be updated from "none" to "no default setting" to hangle new games and rule resets..

**Comment by megas4o** [comment]
This is a brand new save,made in the last version in github.

**Comment by Frodfurgurn1991** [comment]
You need to run BackwardsCompatibility to update the rules.

I just changed the value "do not automatically set assignments" from "none" to "no default setting", like the rest of the RA does and so now any "none" that was present in rules (before the update) is treated as a valid assignment.

**Comment by Frodfurgurn1991** [comment]
I stand corrected, pregAnon did find a bug (hence #1006)
