### ISSUE TITLE
personal training not available any longer

### ISSUE THREAD

**Issue by keramond** [Free-Cities/Free-Cities#1008]
in the new build, the links at the bottom of the mainpage are gone so i can't apply personal training, or is it at a new location? (like head girl, recruiter or bodyguard)

**Comment by keramond** [comment]
"buy slaves" is gone too ;)

**Comment by keramond** [comment]
ok just found the leadership options and "show below" option is not working

**Comment by Weresmilodon** [comment]
Not sure this should have been closed. It's a bug, right? Especially since Below is the default choice.
