### ISSUE TITLE
Difficulty Changing the Title Widget

### ISSUE THREAD

**Issue by freecitiesbandit** [Free-Cities/Free-Cities#1015]
I've been doing some work with the title widget in 'assaywidgets'. Hopefully this will make it easier to add new title variations in the future. But I can't seem to get the game to print any female or futa(nari) titles as anything other than $desc. Hoping I just made an obvious mistake. From some testing, I think the other titles are working correctly (or at least printing in game).

**Comment by DrNoOne0** [comment]
In the muscle section for Null and Futa you have stray quotes.  In both cases the line looks like this:
`<<set $desc = "$desc + " muscle">>`

Removing the first " on both lines should fix it.

**Comment by freecitiesbandit** [comment]
I can't believe it was so simple. Thank you so much.
