### ISSUE TITLE
Cheat edit slave NaN

### ISSUE THREAD

**Issue by pregAnon** [Free-Cities/Free-Cities#1041]
Traced it back here, so less pressure on me to figure it out.

Anyway, changing a slave's clit size in cheat edit slave causes $Beauty to NaN. Not yet sure why, since the flesh description accurately reports the changed asset meaning .clit is being properly set. I suppose I should also pass along that I've been chasing a NaN in the various slave sex act counts (.oralCount, etc) that seems to be related.

**Comment by lowercase-donkey** [comment]
Hey @pregAnon, I can't seem to repro.  For "cheat edit" do you mean export/import with text editor?  And you're just changing the 'clit' variable?

**Comment by pregAnon** [comment]
I mean under cheat mode edit slave option in slave interact.

**Comment by lowercase-donkey** [comment]
Ooh, good one. I see it now.

Sorry, I forgot that option was up there at the top of the screen.

I'll see if a second set of eyes turns anything up!

**Comment by lowercase-donkey** [comment]
Got it.  Cheers!
