### ISSUE TITLE
Does this line ever fire?

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#1085]
https://github.com/Free-Cities/Free-Cities/blob/master/src/utility/assayWidgets.tw#L492

If I'm reading it correctly, it fires if Fundamentalist and Radicalist are both assigned.  But they're exclusive.  Or maybe I'm reading it wrong?

**Comment by kopareigns** [comment]
Both FSGenderFundamentalistLawBeauty and FSGenderRadicalistLawBeauty are toggled between 0 and 1. The line you're looking at checks if their sum is greater than 0. This will be true if either is assigned.

In short, it fires if Fundamentalist OR Radicalist is assigned
