### ISSUE TITLE
Resizing and repositioning the vector art

### ISSUE THREAD

**Issue by freecitiesdev** [Free-Cities/Free-Cities#118]
This is not an issue as such with the code as it is now, but a more general request for help. If there's a more appropriate way to post something like this on GitHub let me know.

I don't know CSS. I suspect it'd be trivial for someone with proper knowledge to go into artWidgets.tw and change the SlaveArt widget div to resize or otherwise manipulate display of the vector art. My ignorant attempts so far haven't accomplished much. Is there someone who can assist with this?

**Comment by 000-250-006** [comment]
I'll take a look at it this afternoon ... what are you looking to do with it? Reduce it in size fixed, or dynamic?

**Comment by freecitiesdev** [comment]
Dynamic. The vector artist and coder (who hasn't been active in a month, leading me to step in) has it set up with an "imageRef" class that's fixed. The slaveArt widget accepts arguments, and getting those arguments to include px height and width would be good.

**Comment by 000-250-006** [comment]
OK I'll take a skeg at the code and see what's going on in there.

**Comment by 000-250-006** [comment]
OK, I'll see what I can figure out from it. Switch to email if you want to discuss? 

    On Monday, March 13, 2017 4:31 PM, freecitiesdev <notifications@github.com> wrote:
 

 Dynamic. The vector artist and coder (who hasn't been active in a month, leading me to step in) has it set up with an "imageRef" class that's fixed. The slaveArt widget accepts arguments, and getting those arguments to include px height and width would be good.—

**Comment by 000-250-006** [comment]
OK, so email replies works :P

**Comment by freecitiesdev** [comment]
Thanks. Go ahead and look at the latest when you get to this, since some unrelated stuff that affects the hrs and divs is happening.

**Comment by freecitiesdev** [comment]
The most pressing current issue here is that my hacky workaround to crop some unused space was to set the div margins to -75 px. This disables links if it overlaps them.

**Comment by 000-250-006** [comment]
#141 should fix it, let me know if it works and I'll clean out the comments for a final version

**Comment by 000-250-006** [comment]
I've been thinking about how these look. I'm assuming just cropping the source images isn't desirable, you want to dump the empty spaces too? I can fix that with CSS trickery too if that's the case, but it might look weird

**Comment by freecitiesdev** [comment]
That's an alternative solution, sure, but not one I can do myself without
it being extremely laborious. I'm sure there's a way for someone with good
photoshop skills to batch it in like, four keystrokes, but that's not
something I can do.

**Comment by 000-250-006** [comment]
@freecitiesdev for reference, what's the copyright status of the vector images? Is it OK to modify them?

**Comment by Bane70** [comment]
Also of note I'm correcting the displaying of the rendered images in the facility end of week code (vector art not showing here for me if it is supposed to), seems some got placed in the wrong spots. I'm placing them where it displays the slave descriptions for the facilities that do that. As that is affecting the way text is being displayed a bit. For the facilities that don't display text for the slaves I guess I'll comment out the code for now.

**Comment by Nov-X** [comment]
Author of the vector images here. Go ahead and make modification to them if need be. I'm on break from adding to them, but would appreciated if I'm in the loop. Let me know if there's questions or help needed.

**Comment by 000-250-006** [comment]
Many thanks! Right now I'm just looking to chunk the whitespace out with some judicious viewbox magic, but I wanted to make sure it'd be all good if I went into them directly to poke.

**Comment by Nov-X** [comment]
Sure man. I originally left the spaces for poses that may involve spreading arms and leg apart, and as well as some sort of gui that assist in conveying information, hopefully your solution can be flexible and allow for easy resizing if those ever come to fruition.

**Comment by 000-250-006** [comment]
In *theory*, viewbox/viewport will only affect the "active" area of the image - they'll still be 1000x1000 but the display co-ordinates will change to only show x of the center and max height.

I'm kind of guessing, I've not played with SVG much beyond greebles :P 

Side note: Thanks for doing these, I never considered how you did it as a technique before. I am so stealing the method :)
