### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by Bane70** [Free-Cities/Free-Cities#127]
When I go and finish off the three remaining reports (Club, CellBlock, and Spa)for their bugs how should I handle the new way it's displaying the slave info? Since the summary part about the facility/leader kinda needs a bit of that info updated. Should I just leave it at the end for now, and correct the bugs? Or try and keep the summary at the top, and the slave "sa reports" after with corrected bugs of course? Or maybe end up having the summary at the end of the slave descriptions?

The area's that is an issue with the summary is the married to PC part, and maybe the income bit if it's to stay at the top.
Also noticed that clubReport depends on "SA serve the public" to populate some vars ($modded, $old, $pure, $slim, $stacked, $unmodded, $XX, $XY, $young), lol explains as to why I noticed my club not doing as well afer I deleted the << silently >> run "SA's". Could place a <<Beauty $slaves[$i]>> in the loops to fix that issue though if they are to remain at the end. Then zero those vars out again before displaying "SA serve the public".

**Comment by 000-250-006** [comment]
How much would the for loop add to the processing overhead?

**Comment by freecitiesdev** [comment]
It's more important to retain the same order of presentation than it is to
be efficient (alas). So I'd say just kill the bugs.

**Comment by Bane70** [comment]
OK just about done with spa report now and the cellblock should be an easy one if I remember right.

**Comment by freecitiesdev** [comment]
Solid work; thank you.

FCD
