### ISSUE TITLE
Issues with Official release and git compiled

### ISSUE THREAD

**Issue by Bane70** [Free-Cities/Free-Cities#140]
I seem to have a strange issue when I downloaded and compiled the git version; when I get to the main menu (new or a saved game) my slaves vector art is on the left, but in the official release it's on the right. going over the changes made on git it don't seem to be anything that would cause this that I can see.

Also of very minor difference the html filesizes are usually smaller from git (obviously before I make any changes), by up to 6kb.

**Comment by 000-250-006** [comment]
This might be related to #118 - working on that one

**Comment by Folant** [comment]
Seems like official release was compliled without https://github.com/Free-Cities/Free-Cities/pull/135/commits/e93c22d7a0e9eea09768c198c48416f42d7e50bd
