### ISSUE TITLE
Missing pull?

### ISSUE THREAD

**Issue by 000-250-006** [Free-Cities/Free-Cities#170]
#161 was closed but not merged. There's 3 commits in there essential.

**Comment by 000-250-006** [comment]
Patch file against upstream/master
[accordion.zip](https://github.com/Free-Cities/Free-Cities/files/862466/accordion.zip)

**Comment by Folant** [comment]
https://github.com/Free-Cities/Free-Cities/issues/171#issuecomment-288346649 : 
@000-250-006 
https://github.com/000-250-006/Free-Cities/blob/8b8bdbcd4d3dcf0edd42915f4096138339c8cb43/src/uncategorized/slaveAssignmentsReport.tw#L317
should be `["Spa Report", $spaNameCaps, $spa, $spaSlaves, $Attendant, "Attendant"]` .

**Comment by 000-250-006** [comment]
Confused ... that's what it is already?

`["Spa Report", $spa, $spaNameCaps, $spaSlaves, $Attendant, "Attendant"],`

**Comment by 000-250-006** [comment]
This is me banging my head against the desk

Good catch, thanks!

**Comment by Bane70** [comment]
Is the patch file still needed? As I seem to have in options the toggle is backwards, disabled is actually enabled. and at least the spa isn't appearing. An I already switched around ["Spa Report", $spaNameCaps, $spa, $spaSlaves, $Attendant, "Attendant"].

**Comment by Folant** [comment]
>Is the patch file still needed? 

Well, I guess it doesn't contain https://github.com/Free-Cities/Free-Cities/issues/170#issuecomment-288519533 at least. #187 also changed slaveAssignmentsReport.tw a bit.
I don't know if @freecitiesdev is going to reopen and then merge #161, or @000-250-006 is going to open new PR later ( if so, when? ). Here's the latest correct version with all of the above changes though.
[accordionfinal.zip](https://github.com/Free-Cities/Free-Cities/files/884112/accordionfinal.zip)

**Comment by Bane70** [comment]
Ah I see what I did, I capitalized $spa for some reason in ["Spa Report", $spaNameCaps, $spa, $spaSlaves, $Attendant, "Attendant"]. Lol that doesn't help anything.

**Comment by Folant** [comment]
>Lol that doesn't help anything.
>As I seem to have in options the toggle is backwards, disabled is actually enabled. 

I can't understand the problem, maybe because it's nearly 4 AM here lol

**Comment by Bane70** [comment]
>I can't understand the problem, maybe because it's nearly 4 AM here lol

I don't know either I made the $spa lowercase and for some reason it's no longer backwards. It's only 9pm here but I've been awake for far too long.

**Comment by 000-250-006** [comment]
I haven't been monitoring git. I've been working on a version that's better optimized, and opens up functions for other areas as well as making it easier for mod authors to use the same functions. I'll get it up this weekend for review.

**Comment by Folant** [comment]
I guess this issue can be closed now.
