### ISSUE TITLE
End of week summaries not showing

### ISSUE THREAD

**Issue by 000-250-006** [Free-Cities/Free-Cities#171]
Not displaying summaries even with everything toggled on.

It's not accordion, the source shows it's not even generating the summaries into the HTML.

![fc-end-of](https://cloud.githubusercontent.com/assets/23348930/24188396/7969ba4a-0e9e-11e7-93c8-d816a174d0db.png)

**Comment by Folant** [comment]
Did the summary have been implemented for this facility? 
#71 #85

**Comment by 000-250-006** [comment]
I thought the goal for this iteration of facility reports was to enable full individual reports be available for all of them, when they were previously limited to Master Suite and the Club? Did I misunderstand?

**Comment by Folant** [comment]
I guess it's enabled for Club/Master Suite/Cellblock/Spa only, for now

**Comment by 000-250-006** [comment]
This is what happens when we miss staff meetings

I'll close this

**Comment by Folant** [comment]
also it seems Spa report broken in the current build

**Comment by Bane70** [comment]
Lol. I'm still working on the facilities, and there is still at least the married issue with displaying the slaves individul SA's, In the summary it could say married to PC and in the slaves ind. report it could say not married anymore. I could have that line be displayed after the saRelationship. or leave it where it is. As out of my testing I've only seen it happen once out of way too many end of weeks.
I think there is still a bug in saRelationship as well or my game glitched as I also only seen it once display the "become emotionally attached' and then the next sentence said she was "looking elsewhere"

I can change it to display all the summaries as it's been more or less set up for that to be done. Just a matter of a few cut n' pastes. I wasn't the one that originally started converting the SA's to be displayed.

**Comment by 000-250-006** [comment]
If you're taking the array route, are you open to a suggestion?

One of the things I wanted to do was standardize how facility data is stored. Right now they're all the discreet variables (like $clinic (for capacity), $clinicSlaves (occupancy) and $Nurse ... I had the thought that creating a multi-dimensional array/object would make it easier for storage and for people adding new facilities down the line. It'd also make it easier to walk the array for arcology-wide stuff like the reports, because it'd open up going with each() instead for a for->if loop.

Might not be explaining that right. But, I can pseudo-code it into my /develop tree if you're interested in seeing what I'm thinking?

**Comment by 000-250-006** [comment]
This is what I'd already worked up but rejected when stubbing my ARIA-fied mod to do Accordion. The variables point to existing ones, but they'd be actual values in my idea above

    <<set $facObj = {
        brothel: {
            passage: "Brothel Report",
            capacity: $brothel,
            occupants: $brothelSlaves,
            boss: {
                ID: $Madam,
                title: "Madam"
            },
        },
        club: {
            passage: "Club Report",
            capacity: $club,
            occupants: $clubSlaves,
            boss: {
                ID: $DJ,
                title: "DJ"
            }
        },
        arcade: {
            passage: "Arcade Report",
            capacity: $arcade,
            occupants: $arcadeSlaves,
        },
        dairy: {
            passage: "Dairy Report",
            capacity: $dairy,
            occupants: $dairySlaves,
            boss: {
                ID: $Milkmaid,
                title: "Milkmaid"
            }
        },
        servantsQuarters: {
            passage: "Servants' Quarters Report",
            capacity: $servantsQuarters,
            occupants: $servantsQuartersSlaves,
            boss: {
                ID: $Stewardess,
                title: "Stewardess"
            }
        },
        schoolroom: {
            passage: "Schoolroom Report",
            capacity: $schoolroom,
            occupants: $schoolroomSlaves,
            boss: {
                ID: $Schoolteacher,
                title: "Schoolteacher"
            }
        },
        spa: {
            passage: "Spa Report",
            capacity: $spa,
            occupants: $spaSlaves,
            boss: {
                ID: $Attendant,
                title: "Attendant"
            }
        },
        clinic: {
            passage: "Clinic Report",
            capacity: $clinic,
            occupants: $clinioSlaves,
            boss: {
                ID: $Nurse,
                title: "Nurse"
            }
        },
        cellblock: {
            passage: "Cellblock Report",
            capacity: $cellblock,
            occupants: $cellblockSlaves,
            boss: {
                ID: $Wardeness,
                title: "Wardeness"
            }
        },
        masterSuite: {
            passage: "Master Suite Report",
            capacity: $masterSuite,
            occupants: $masterSuiteSlaves,
            boss: {
                ID: $Concubine,
                title: "Concubine"
            }
        }
    }
    >>

**Comment by Bane70** [comment]
>>If you're taking the array route, are you open to a suggestion?
I definitely am always open to suggestions. I'm assuming that would also maybe hold the other facility vars as well for upgrades/activated and such?
I've thought about doing such as well in the past. But never really did anything beyond that. I also had thought about changing the Leaders $Madam etc. over to just an .ID and .Index as well as that would get rid of the sync issues (and maybe a bit of speed gain). As I used to always get a bodyguard event to train her and she would already of gotten her training done for $combat. I assume the event was/is reading the $bodyguard info and not the $slaves[...]. I've not gotten that event in ages though so maybe it got fixed.

**Comment by 000-250-006** [comment]
Yeah, I was thinking putting it into an array/object would let you have a facility with 

    brothel: {
        passage: "Brothel Report",
        capacity: 15,
        occupants: 7,
        boss: {
            ID: 24,
            title: "That bitch in the back office"
        }
        upgrades: 3
    }

using the actual values in there. That way if someone comes along with another facility, they can just plug it in, and the naming would be clear for everyone to reference.

That and it opens each() up for use, which is going to be faster processing loops.

In theory, doing it this way could eventually lead to only needing one facility report passage, that can be used for end of week *and* individual facility views, even
