### ISSUE TITLE
the compile-script won't work out of the box

### ISSUE THREAD

**Issue by fcg-throwaway** [Free-Cities/Free-Cities#281]
On Linux x64 using the bash-shell I get an error, when I run the compile-script:

> "rm: cannot remove 'src/config/start.tw': No such file or directory"

Creating an empty file in src/config/start.tw fixed the issue.

Imo the problem is that the script aborts, if it can't remove the mentioned file because it doesn't checks if the file exists before it tries to remove it.

There might be a similar bug in the compile-script for windows, but I have no windows installation to test it.

**Comment by fcg-throwaway** [comment]
nvm https://github.com/Free-Cities/Free-Cities/commit/4c531bc716a8631e4db7d0f30a9689da2ca47e34 fixed this issue

**Comment by Bane70** [comment]
If windows can't find the file to delete it just continues with the next command, but it does display saying it cant find it. Though for me I can use a switch to suppress the msg. But then again I use tcc as my command console, I had to edit my .bat file as I have my console set to using Unicode so when it generates start.tw it was originally doing it also in Unicode and not ANSI.
