### ISSUE TITLE
Credit for work on GitHub

### ISSUE THREAD

**Issue by freecitiesdev** [Free-Cities/Free-Cities#327]
I'm posting this as an Issue because I'm not aware of a way to post an announcement that all contributors will see. If there is such a way, please let me know.

**If you have contributed content through Git and would like to be credited, you need to let me know that you want credit.** Since FC is an adult game, I don't put contributors' handles in the credits unless I get express permission to do so. So if you'd like to be immortalized for your work here in the FC credits, email me with your preferred name and what you did.

**Comment by corncobman** [comment]
You already have my permission for whatever, but just in case you need me to state it here, you have my permission for whatever.

**Comment by freecitiesdev** [comment]
Of course. I'll add a generic line to your credits about git bugfixes; let
me know if there's anything else major you want credit for. Apologies, but
I long ago lost the plot of who's done exactly what.

FCD

**Comment by Bane70** [comment]
Same with me you already have my permissions.

**Comment by freecitiesdev** [comment]
Thanks for the confirmation; this was mostly for new people. Feel free to
update your own entry in the credits whenever you feel like it. That's the
best solution, really; I'll always double check changes to that passage.

FCD
