### ISSUE TITLE
RA's autosurgery and HG quarters' link are broken

### ISSUE THREAD

**Issue by kar-dragon** [Free-Cities/Free-Cities#369]
it seems that the rework on the RA page broke the autosurgery options, since my config for the lactation implants was to be implanted on every girl but it wasn't happening.
about the HG quarters, the text is the base white as opposed to the blue color of a link and is not clickable, certainly an oversight, but i though it was better to let you know (it is still possible to access via the old menu).

**Comment by serveral1** [comment]
yeah, RA seems to be broken atm for me as well. rules that are supposed to be only applied to certain slaves are being applied to everyone

**Comment by DrNoOne0** [comment]
Pull #370 Should have fixed the HG quarters issue.

**Comment by fcpmanon** [comment]
@serveral1 can you give a specific example?  I just tested a rule with specific slaves and it only affected the slaves I chose.

Found issue with autosurgery rules; will add to my pending pull request.

**Comment by fcpmanon** [comment]
I should note that RA autosurgery only happens during the end-of-week report phase, not when you "apply rules assistant" manually.

**Comment by kar-dragon** [comment]
it didn't work even during end the of the week report

**Comment by fcpmanon** [comment]
Provide a saved game that exhibits the problem and tell me which slave you expected the RA to work on.

**Comment by kar-dragon** [comment]
it seems to have fixed itself on the last patch, besides, i haven't kept the save where that happened

**Comment by serveral1** [comment]
sorry for the lack of response but yeah, i can also confirm that the issue is gone.

**Comment by kar-dragon** [comment]
then, since the issues have been solved, i'll be closing the topic
