### ISSUE TITLE
RA, Smart piercing fetish target

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#377]
Currently on individual slaves these are the options:

`Vanilla | Oral | Anal | Boobs | Sub | Dom | Humiliation | Preg | Pain | Sadism | Men | Anti-men | Women | Anti-women | All sex | No sex `

However, RA options only list these, as well as "no default":

`Vanilla | Oral | Anal | Boobs | Sub | Dom | Humiliation | Pregnancy | Masochist | Sadist`

Currently DC dev's prefered produces (I think) a smart piercing target of "all," so I know the RA can handle it, see:

` "all", clitSettingSecondary: "$currentRule.clitSettingSecondary"`

RA should be updated to be consistent (Preg/Pregnancy, Pain/Masochist, Sadism/Sadist)  and include 

`Men | Anti-men | Women | Anti-women | All sex | No sex`

**Comment by freecitiesdev** [comment]
This is not well explained at present.

Slaves' individual menus list the possible settings of SPs. The RA options on the other hand list **SP goals.**  If you want the RA to direct the SP to raise libido, tell it to target "nympho" libido level and it'll apply the "all" SP setting until each slave gets there. This way, the RA can be told to reach three different goals for each slave using the SP intelligently.

**Comment by lowercase-donkey** [comment]
Thanks FCdev.

So the "all" rule is sorta depreciated as a user choice, and the other options adjust the strength and target gender of sex drive.  Makes sense.

**Comment by lowercase-donkey** [comment]
Sorry, re-opening for the "(Preg/Pregnancy, Pain/Masochist, Sadism/Sadist)" consistency thing.  Derp.

**Comment by freecitiesdev** [comment]
That's fair. To be clearer, "all" still exists as a clit setting, so you can select it manually. It doesn't exist as a rule setting since the various libido targets use "all" and "none" intelligently, until the target is reached.
