### ISSUE TITLE
Minor: "Drug Regimen" name.

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#380]
Not sure how easy it is to change, but the RA "drug regimen" category has become much broader than "drugs," including braces and muscles.

Maybe it could be called "Slave Formation" or "Slave Shaping?"  "Physical forming?"

**Comment by fcpmanon** [comment]
Slave Shaping works for me, but I'll wait for other opinions.

**Comment by freecitiesdev** [comment]
Fixed.
