### ISSUE TITLE
Minor: "Corsetage" in RA is "Body Accessory" on individual slaves

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#382]
`Corsetage: no default setting. No default setting | None | Tight | Extreme `

`Body Accessory: none. None | Tight corset | Extreme corset `

Is corsetage a subset of BA?

**Comment by fcpmanon** [comment]
Different names, same thing.  Corrected in #392

**Comment by lowercase-donkey** [comment]
Before closing, RA options should be updated as well as title.  Currently RA reads:

`Body Accessory: No default setting | None | Tight | Extreme 

Tight what?  Corsets of course.

I'm also noticing pregnant bellies don't show up here if they were purchased, only on individual slaves.

**Comment by fcpmanon** [comment]
addressed in #441
