### ISSUE TITLE
Divergence between RA and unique slave settings, some minor

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#384]
Typical punishment/reward is on the same line in unique slaves, two lines in RA.

Living standard options are in reverse order between unique and RA.

"Non-assignment orgasm rules" vs "release rules"

"Go naked" vs "nude"

Harsh clothes vs Nice clothes: categories reversed in order, labeled differently (sometimes parenthesis for "nice/harsh," sometimes not) and are scrambled in terms of items.  I understand wanting to keep *nice/slutty* items together, but I don't understand the ordering of the rest of the list.  Perhaps change variants to `nurse (slutty)` and then alphabetical?  While keeping FS at the end? #385

Collar: just easier to put them all here, pretty wild divergence:

Unique slaves:
`None | Tight steel | Cruel retirement counter | Uncomfortable leather | Shock punishment | Dildo gag | Neck corset | Stylish leather | Satin choker | Heavy gold | Pretty jewelry | Nice retirement counter | Leather with cowbell`

RA, plus "No default collar" setting, of course
`No collar | Steel | Cruel retirement | Harsh leather | Shock | Dildo gag | Neck corset | Nice leather | Satin choker | Gold | Pretty | Nice retirement | Cowbell `

Shoes too:

`Go barefoot | Flats | Heels | Thigh boots | Painfully extreme heels`

`Barefoot | Flats | Heels | Boots | Extreme heels `

"Body Accessory" vs  #"Corsetage." #382

Chastity see #379

Genuinely confused about "drugs" vs "growth regimen for healthy slaves."

"Health" vs "Health drugs"

Aphrodisiacs is on the same line as health in Unique, but not RA

"Diet" vs "Muscles," although I understand they are different things they seem similar.

**Comment by fcpmanon** [comment]
Body Accessory changed to Torso Accessory in #443

**Comment by fcpmanon** [comment]
Open issue - muscles setting alone has no effect if diet is "no default setting"
