### ISSUE TITLE
Minor: Capitalization in clothing titles

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#386]
Most clothing titles listed below:

```
Bangles
Bodysuit
Cheerleader outfit
Clubslut netting
Cutoffs and a t-shirt
Fallen nun
Haltertop Dress
Hijab and abaya
Latex catsuit
Leotard
Maid (Nice)
Maid (Slutty)
Military Uniform
Mini Dress
Nice lingerie
Nurse (Nice)
Nurse (Slutty)
Schoolgirl
Silken Ballgown
Skimpy Battledress
Slave Gown
String bikini
Succubus Costume
Suit (Nice)
Suit (Slutty)
FS Chattel habit
FS Conservative clothing
FS Japanese
FS Western clothing
```

This is a very small thing, but caps are InCoNsIsTeNt.  If they are treated as proper titles, then the following should be caps: outfit, netting, nun, etc.  Or else words like Gown and Costume should probably be lower case.

As it is, we have "catsuit" and "Dress."

**Comment by lowercase-donkey** [comment]
Same is true for collars.

**Comment by freecitiesdev** [comment]
Should be fixed in the next update.
