### ISSUE TITLE
Bug: Multiple slaves entering schoolroom when a single slave is assigned

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#391]
Build 1005.

So this is a weird one.  I noticed that the main screen listed the schoolroom as 2/10, which did not match the larger number of students in the room.  I released a single student, and it released all of them.  The counter went to 0/10.  

However, now when I assign any slave to the schoolroom, *allll* those other slaves drop what they are doing and go to school too.

This seems to be connected with assigning them at some point directly from, Brothel > Schoolroom.  In fact, if you go to the brothel tab, you can see that many people who are in the Brothel are technically also "taking classes" or even RESTING!  Slackers!

[stuck in schoolroom.zip](https://github.com/Free-Cities/Free-Cities/files/978074/stuck.in.schoolroom.zip)

Edit, oh shit, now the number of people in my brothel is bugged.  I'll try resting everyone.

Edit 2; Nope, completely bugged out now.  Most slaves are in a superposition.  Only a few came back to the main list.  The others insist they are in the brothel or school, but cannot be found there when you enter the buildings.

**Comment by fcpmanon** [comment]
hopefully resolved once #392 gets merged

**Comment by lowercase-donkey** [comment]
Seems to be fixed for me.
