### ISSUE TITLE
When appointing Madam, Nurse, etc, include slaves assigned to facilities

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#393]
It's currently difficult to find who has the background to be a good shrink, nurse, warden, etc.  Basically, I'm clicking one at a time to remove every slave from the brothel.  Then choosing the best one for the job.  Then sending them all back to the brothel.

It would be helpful if every slave was checked for potential to be a schoolteacher, not just the ones chilling on the main screen.

Alternately, a "mass eject" button would work, where I could kick everyone out of a building at once, but then I'd still need to figure out where they all return when I am done. Possibly a way to simply assign all those who are whoring to the brothel?  Wait, I can probably make a rule for that.

Edit: making a rule for that is bad news.  I set up a rule that said (Always > whoring job > go to brothel.)  Got a very strange duplication bug where new recruits went straight into the brothel, when they appeared at all.  Although I paid the cost of each slave as I recruited, odd numbered slaves would not come in at all and even slaves arrived duplicated.

**Comment by fcpmanon** [comment]
Duplication bug will be fixed with #392 

Added "show slaves in facilities when selecting for leadership positions" to #392
