### ISSUE TITLE
Build number is wrong

### ISSUE THREAD

**Issue by MegaPramuk** [Free-Cities/Free-Cities#397]
Yesterday, I've built from master and saw it has 1005 commits already (according to the build number portrayed in the main menu at least) but after pulling and building again today, it's still 1005. 
I don't really understand the structure of this project (or rather, what exactly .tw files are) but if I'm not mistaken, the variable for this is declared in ./src/init/startInit.tw.
There should be some automation going on for the builds instead of hardcoded values.
With `git rev-list HEAD --count` one can easily find out the current commit count. And with sed (in ./compile at least) one could change $releaseID.

**Comment by freecitiesdev** [comment]
$releaseID is being looked at.
