### ISSUE TITLE
Better sorting for job/facility options, especially in RA.

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#408]
I'm wondering if we can line these up a little better as well, minimally to improve readability.  Here, I think, inner logic is more important than alphabetical.  Here is how it is in RA currently:

| ASSIGNMENT | None | Rest | Fucktoy | House Servant | Confined | Whore | Public Servant | Classes | Milking | Gloryhole 
| --- | ---| --- | ---| --- | ---| --- | ---| --- | ---| --- | 
| FACILITY | None | The Head Girl Suite | The Brothel | The Club | The Arcade | The Dairy | The Servants' Quarters | The Master Suite | The Schoolroom | The Spa | The Clinic | The Cellblock 

The "none first" logic is pretty universal in FC, and in keeping with popular options being early in lists.  However, after things things diverge. First, does this pairing between facilities and jobs make sense?

None | None
| --- | --- |
| Rest | The Clinic 
| | The Spa
| Fucktoy | The Master Suite 
| House Servant | The Servants' Quarters 
| Confined | The Cellblock 
| Whore | The Brothel
| Public Servant | The Club |
| Classes |  The Schoolroom 
| Milking | The Dairy 
| Gloryhole | The Arcade
| | The Head Girl Suite |

Here I simply moved facilities to line up with jobs.

Logically, this can be broken down into "give this slave something" and "have this slave give something." Perhaps sorting like this?

None | None
| --- | --- |

|SHAPE SLAVE WITH| |
| --- | ---
| Rest | The Clinic 
| Confined | The Cellblock 
| Classes |  The Schoolroom 
| | The Spa 

|HAVE SLAVE WORK AT||
| --- | --- |
| Fucktoy | The Master Suite 
| House Servant | The Servants' Quarters 
| Whore | The Brothel
| Public Servant | The Club |
| Milking | The Dairy 
| Gloryhole | The Arcade
| | The Head Girl Suite |

I think the order can be improved even more, but for simplicity, I'm keeping original ordering as much as possible, and this would give us:

Assignments: `None | Rest | Confined | Classes| Fucktoy | House Servant | Whore | Public Servant | Milking | Gloryhole `

Facilities: `None | The Clinic | The Cellblock | The Schoolroom | The Spa | The Master Suite | The Servants' Quarters| The Brothel | The Club | The Dairy | The Arcade | The Head Girl Suite | `

It could make things easier to find in an increasingly longer list.  I'm not sure if it makes sense to label the Work/Shape categories explicitly, or just leave people to figure it out on their own.  Space can be tight and the page is busy as it is.

**Comment by lowercase-donkey** [comment]
The order is also different in the reports at week's end: 
Brothel, Club, Arcade, Dairy, Servant's Quarters, Spa, Clinic, Cellblock, Mastersuite.

Here the order is mostly WORK, then SHAPE, with the exception of the Master Suite.

**Comment by fcpmanon** [comment]
partially addressed in #441

**Comment by fcpmanon** [comment]
a limiting factor in the code is that certain assignments allow fuckdolls (rest, fucktoy, arcade) while the rest do not.  it's convenient to group all the others together in a single IF block
