### ISSUE TITLE
Divergence between RA and unique slaves: Assignments/facilities

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#409]
Now with tables!  Tables just for git, it's easier to compare several lines this way.

Assignments:

| RA: Apply to assignments: All | Rest | Fucktoy | Subordinate Slave | House Servant | Confined | Whore | Public Servant | Classes | Milking | Gloryhole |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- 
| Unique: Assignment: | Rest | Fucktoy | Subordinate slave | Servant | Take slave classes | Confine her | Whore | Public servant | Glory hole | Get milked | Let her choose her own assignment | Assign her to her current task for another month 

Facilities:

| RA: Apply to facilities: | All | The Head Girl Suite | The Brothel | The Club | The Arcade | The Dairy | The Servants' Quarters | The Master Suite | The Schoolroom | The Spa | The Clinic | The Cellblock 
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- 
Unique: Transfer to: | Brothel | Club | Dairy | Servants' Quarters | Master Suite | Spa | Clinic | Schoolroom | Cellblock | Arcade 

As you can clearly see, not only does order diverge between the two pages, but naming does as well.

Let me temporarily correct order so it is easier to compare naming:

| RA: Apply to assignments: All | Rest | Fucktoy | Subordinate Slave | House Servant | Confined | Whore | Public Servant | Classes | Milking | Gloryhole |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- 
| Unique: Assignment: | Rest | Fucktoy | Subordinate slave | Servant | Confine her | Whore | Public servant | Take slave classes | Get milked | Glory hole |  Let her choose her own assignment | Assign her to her current task for another month 

I simply had to move classes down, and switch milking/glory hole.  Should be simple to standardize naming (House servant vs servant, Gloryhole vs "Glory hole" etc.)

Facilities is a bit of a mess: I moved arcade and spa

| RA: Apply to facilities: | All | The Head Girl Suite | The Brothel | The Club | The Arcade | The Dairy | The Servants' Quarters | The Master Suite | The Schoolroom | The Spa | The Clinic | The Cellblock 
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- 
Unique: Transfer to: | | | Brothel | Club | Arcade | Dairy | Servants' Quarters | Master Suite | Schoolroom | Spa | Clinic | Cellblock | 

Here naming is good except one has "the" for everything and the other does not.  See #410

#408 would be good to check, there should be some kind of logic to the order here.  It's pretty random right now.

**Comment by fcpmanon** [comment]
partially addressed in #441
