### ISSUE TITLE
Duplication is still present

### ISSUE THREAD

**Issue by kar-dragon** [Free-Cities/Free-Cities#412]
the duplication issue is still present in the last release, slaves can still be duplicated if a RA rule send them to some facility before the start of the new week, most notably, when my rule for unhealthy slaves send them to the clinic when their health was less than 20, a clone slave would appear there too. i changed the rule to be less than 0, but any ill slave still is duplicated by this.

also, i am at week 21 and still can't buy the last few tiles of my arcology (yes, it was a cheat start).
[free-cities-CS-0.10.1.zip](https://github.com/Free-Cities/Free-Cities/files/981305/free-cities-CS-0.10.1.zip)

**Comment by fcpmanon** [comment]
maybe addressed by #441 - please try again after that gets merged in
