### ISSUE TITLE
Enhancement: Adding slots for outfits.

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#416]
I don't know if there is a roadmap for enhancements, but I have a suggestion for enhancing clothes.  Currently outfits have three slots: "clothes" in general, Shoes, and Collar (and technically glasses/contacts, special cases.) I suggest adding hats, gloves, and costume tails.  Without going too wild, I have tried to pick some items that easily compliment existing clothing.

| Clothes | Hats | Gloves | Tails
| --- | --- | --- | ---
| Go naked | none | none | none |
| *Harsh clothes:*
| Uncomfortable straps | Nose hook | Finger binding
| Shibari ropes | Dildo gag *(move from collar)*
| Restrictive latex | Gas mask | Mittens
| Penitent nun | Nun's Veil | Rosary/Holy book
*Nice clothes:*
| Nice lingerie | | | Angel wings
| Slutty maid | Maid cap | Feather duster
| Nice maid |
| Haltertop Dress 
| Mini Dress 
| Silken Ballgown | Tiara | Opera gloves
| String bikini 
| Clubslut netting | | Long latex gloves
| Cheerleader outfit | | Pom-poms
| Cutoffs and a t-shirt | Stetson hat
| Slave Gown 
| Slutty Suit 
| Nice Suit 
| Slutty Nurse | Nurse cap
| Nice Nurse 
| Schoolgirl 
| Bodysuit 
| Latex catsuit | Latex Mask | Short latex gloves
| Leotard 
| Skimpy Battledress | Military Beret | Fingerless gloves
| Military Uniform | Military Cap | Dress gloves
| Fallen nun 
| Hijab and abaya 
| Bangles | | Bangles' Bangles
| Succubus Costume | Succubus Horns | Trident | Devil Tail/Devil wings
| FS Bunny outfit | Bunny ears | | Bunny tail
| FS Conservative clothing 
| FS Chains | | Handcuffs
| FS Western clothing | 
| FS Body oil | 
| FS Chattel habit | 
| FS Toga | Garland
| FS Kimono | 
| FS Harem gauze | Thin veil
| FS Slutty Qipao | 
| | Bonnet
| | Cow horns | Hoof gloves | Cow tail 
| *If desired, perhaps purchasable separately:* | $animal ears | $animal paws | $animal tail

- I'm not sure if finger restricting gloves like finger binding or mittens would impact any scenes, it may not be worth adding (or it's possible to assume they are removed for relevant scenes, just as the dildos are.)
- I'm not sure if adding things like books and tridents to a hand slot would make glove descriptions too complicated. 
- Also, just as a luxury room is kind of a reward, perhaps a few "special" hats could be added.  A slave crown or Pope hat (Mitre) for HG or Concubine.
- If you wanted to get really fancy, you could add a mouth slot.  Dildo gag is already here, but there is ring gag, ball gag, onahole gag, and all sorts of other gags.
- If you wanted to get really fancy, you could also add a stocking slot.  Latex short/tall, striped, pantyhose, etc.
- Perhaps later there could be some sort of matching outfit bonus.

**Comment by freecitiesdev** [comment]
> I'm not sure if finger restricting gloves like finger binding or mittens would impact any scenes, it may not be worth adding (or it's possible to assume they are removed for relevant scenes, just as the dildos are.)
Yes, horribly, to the point where I'll veto it.

Otherwise, these should all be pretty easy to add. The best way to see these good suggestions in game is to get on Git as a contributor.

**Comment by lowercase-donkey** [comment]
@freecitiesdev How do I add a new category to activeSlaves?  So if I want to make activeSlave.hats, or activeSlave.gloves?

**Comment by freecitiesdev** [comment]
Unless you are extremely confident with the code, you ask me to do it. The
short version is, you find every place that a $slave array is set up and
insert your new variable.

**Comment by lowercase-donkey** [comment]
Wow, that's annoying.

I'd like to work on this, if it's all right with you @freecitiesdev, but I suppose thoughtful consideration is in order if we are expanding slots, so you don't need to do it again for outfits.

I don't want to drown out the settings page with slot after slot either (I think it would be pretty easy for me to add an "outfits" category that changes someone into maid clothing for every slot though.)

Could we add these?

- Hat
- Gloves
- Back
- Stockings/leggings
- Gag

Is that too much?  Are there slots I should work on but didn't list?  I don't think we need pants, for obvious reasons.  Pantsu/socks distinction, or just stockings ok?

**Comment by freecitiesdev** [comment]
Twine wasn't meant for this, and I'm not half the coder I'd have to be to
find elegant solutions.

That's too much. The tradeoff here is between fun for the people who will
enjoy the new slots, and slowdown. Keep in mind, not only will these bloat
the menus, but they'll also add more stuff for the Rules Assistant to do.

**Comment by lowercase-donkey** [comment]
I'm taking a stab at it.  (I'd kill for some kind of database, lol)

I'll put the fork up in a bit.  It's looking like you don't really declare variables the way I thought you did, you just kind of add as you go?  I'll have to look backwards to make sure slaves initialize properly though.

And yeah about Twine, heh.  Looking at the way clothing is sorted it's such a pain in the ass to add it, because it's sorted by body part, not by clothing item.  Fun though!

**Comment by fcpmanon** [comment]
Keep in mind $ variables are global while _ variables are semi-local (they get cleared when you go through a <<link>> or [[passage]] transition).  At least, that's my understanding.  If you don't need a variable to be used elsewhere, it's safer to use _ prefix.

**Comment by fcpmanon** [comment]
Take a look at how the rulesAssistant.tw includes sections of interaction menu using widgets (defined in raWidgets) by creating target sections (span id=xyz defines a target area, then the widget uses replace #xyz to fill it in, and we call the widget again when we need to update that section).  rulesAssistant.tw avoids duplicating the sections that are included-by-widget by doing a short pause after page load (to allow enough time for the spans to be set up) by using the `<<timed>>`  macro.  I think that is a good pattern to follow.
