### ISSUE TITLE
Minor: Tunics not togas.

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#418]
Togas are something of a big deal in frat life, and perhaps that is where they are being drawn from.

But if my Arcology is going to revive Roman culture, slaves would never never EVER wear a toga:

> Citizenship carried specific privileges, rights and responsibilities.[29] In Roman territories, the toga was explicitly forbidden to non-citizens; to foreigners, freedmen, and **slaves;**
https://en.wikipedia.org/wiki/Toga#Togas_in_civil_life

The toga is a mark of being a citizen and should perhaps be granted a slave with their freedom.

However, the day to day life of a *servus* or *ancilla* is simply the [*tunic.*](http://www.tribunesandtriumphs.org/roman-clothing/roman-slaves-clothing.htm)  

It's basically already here too, as the slave gown.  Can I suggest merging them, or would that trash saves?  The easy fix is just to change the name of the toga though.

**Comment by freecitiesdev** [comment]
You know this, I know this, but most players don't know this. The Revivalisms aren't meant to be 100% accurate anyway. I'll fix this, though.
