### ISSUE TITLE
Enhancement: Expanding clothing selection

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#419]
We seem to be missing some basics: We have nurse, but no police/firefighter.  We have student, but no teacher.  We have oil, but no bodypaint.  Cheerleader, but no athletic clothing. Silken ballgown, but no princess.

How difficult is it to add new clothing?  Is there a guide I could follow?

**Comment by freecitiesdev** [comment]
Not particularly difficult. Honestly, I'd recommend getting yourself set up for Git contribution, and then doing a notepad++ search-all for some of the existing clothing options, e.g. search "slutty suit". That'll show you the places clothes appear.
