### ISSUE TITLE
Bug: Main menu event

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#495]
> Sienna walks past your desk with the swaying steps she must take in her high heels. She is on her way to get treatment in the clinic; she rushes by, hurrying to her next task. Her sister Mila walks past your desk with the swaying steps she must take in her high heels. She is on her way to she rushes by, hurrying to her next task. Summon them both

A lot of redundant text here, but maybe I broke something in a tweak I made in #494.

**Comment by fcpmanon** [comment]
"She is on her way to she rushes by, hurrying to her next task." is missing something after "to"

**Comment by fcpmanon** [comment]
missing default case in WalkPast.tw at line 463 -- need to add:

<<default>>
  _partnerSlave.assignment;

will be fixed by my pending merge request #490

**Comment by fcpmanon** [comment]
@lowercase-donkey you can close this now
