### ISSUE TITLE
RESSTR stands for what?

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#498]
I'd like to add a comment to the top of a few files to clarify acronyms.  What is the TR for?

RESS: Random Event, Single Slave
RESSTR: Random Event, Single Slave ????  TRained? TRaining?
RETS: Random Event, Two Slaves
RECI: Random Event, Check In
REFI: Random Event, Fetish Interest

PESS: Player Event, Single Slave
PETS: Player Event, Two Slaves

**Comment by fcpmanon** [comment]
I am equally baffled by RESSTR.  Events are devoted educated slave, young PC age difference, old PC age difference, desperate null.  How are these different from RESS events like happy dance, repressed anal virgin, PA servant, PA flirting, sexy succubus, bad dream, etc.?  The conditions checks for RESSTR and RESS events are intermingled in the same "STANDARD EVENTS" section of RandomIndividualEvent.

**Comment by lowercase-donkey** [comment]
Yeah, full list here:

RESSTR:

- devoted educated slave
- young PC age difference
- old PC age difference
- desperate null
- nice guys
- lazy evening
- devoted shortstack
- servant maid

RESS

- happy dance
- PA servant
- PA flirting
- sexy succubus
- trusting HG
- sleeping ambivalent
- bad dream
- ignorant horny
- mods please
- sore shoulders
- confident tanning
- a gift
- devoted exhibition
- devoted lotion
- devoted nympho
- permitted masturbation
- terrified inspection
- cooler lockin
- kitchen molestation
- vocal disobedience
- huge tits
- age implant
- birthday
- penitent
- not my name
- tendon fall
- obedient shemale
- devoted old
- fearful humiliation
- newly devoted sunrise
- spa boobs
- cow milking
- retching cum feeding
- subjugation blues
- too thin for cum diet
- breast expansion blues
- ara ara
- gaped asshole
- passing declaration
- im scared
- arcade sadist
- ass fitting
- comfortable seat

I don't see the common thread.

**Comment by freecitiesbandit** [comment]
IIRC, FCDev mentioned to me once that this is where he holds new events before introducing them into RESS. Just for easier bugtesting.

**Comment by lowercase-donkey** [comment]
TR could be Test Release then?

If that's the case, why are some events standalone and some are in the snowballs?  It would be nice to be able to give some guides for people that want to add events. (Like, well, me.)

**Comment by freecitiesdev** [comment]
Apologies for the confusing code. Free Cities was originally written on the assumption that a grand total of one person would ever see the code - me. That's also why there's no comment system at all.

> IIRC, FCDev mentioned to me once that this is where he holds new events before introducing them into RESS. Just for easier bugtesting.

This is correct. RESS is enormous, so it's much easier to find bugs in new events if they're in a mechanically identical but much shorter passage.

> RESSTR

I used TR because I'd seen it before. IIRC the TR actually stands for "test realm."

**Comment by lowercase-donkey** [comment]
Hey, no shame!  Thanks for sharing the codebase with all of us.  I just want to help it grow.
