### ISSUE TITLE
helots and sweatshops

### ISSUE THREAD

**Issue by tc-k** [Free-Cities/Free-Cities#531]
Both the display in manufacturing.tw and the earnings for them in arcmgmt.tw has got to be bugged (right now a fully staffed sweatshop makes less than a partially filled one), but to fix them I need to know what the math is supposed to be.

So, a helot adds 10 to earnings. This is the base.
How much does a partially filled sweatshop supposed to add?
How much does a fully-staffed sweatshop supposed to add?

Also, buildingWidgets.tw is bugged. As I looked into my savegame I discovered that I have 23 Sweatshops. Investigation shows that $Sweatshop is a permanent variable. So every turn when SectorCount widget in buildingWidgets.tw checks how many Sweatshops there are, $Sweatshop gets incremented. I suggest resetting $Sweatshop to zero before counting sectors. EDIT: NM, decided to fix that myself since it's obvious.

EDIT: Also discovered that the number of helots can go over the cap. Probably the weekly helot recruitment doesn't check for caps? Also some events that adds helots probably should check for helot cap.

**Comment by fcpmanon** [comment]
Yes, the weekly menial recruitment (e.g., from encourage migrant enslavement policy) doesn't check for caps; it's effectively a small boost weekly income if you have maxed menials, as excess over cap are sold automatically whenever you access the buy slaves passage.

**Comment by tc-k** [comment]
Regarding how much a sweatshop is supposed to add, I'm going to guess that the intention is as follows:
Each helot adds 10 to _earnings.
If the helot is working at a sweatshop, add 10 more to _earnings.
If the sweatshop is fully staffed, add 2000 to _earnings for the full sweatshop.

Examples: Say there are 300 helots and no sweatshop. The helots will add 3000 to earning. If we add a sweatshop, the helots add 3000 more for a total of 6000. Adding a second sweatshop does nothing.

Say there are 1 sweatshop and 300 helots. That will net 6000. However, if there are 500 helots, the earned money would be 5000 for the helots + 5000 for the presence of the sweatshop + 2000 for having the sweatshop be fully staffed for a total of 12000.  If the player buys 500 more helots, the earned money would be 12000 like previously + 5000 for the new helots = 17000. To max out earning for those 1000 helots he'll need to add another sweatshop. That will make his total earnings 24000. If he then sells 100 helots, so there are 900 helots working in 2 sweatshops, the earnings would be 12000 for the helots working in the fully staffed sweatshop + 8000 for the helots working in the partially staffed sweatshop.

Please comment if this is right or off.

**Comment by tc-k** [comment]
Implemented and pull request submitted.
