### ISSUE TITLE
For review: documentation idea in RESS and others

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#547]
```
/* This is one of several files that contains and organizes many different events.	*/
/*  genericPlotEvents.tw												*/
/*  PESS.tw: Player Event, Single Slave									*/
/*  PETS.tw: Player Event, Two Slaves									*/
/*  RECI.tw: Random Event, Check In									*/
/*  REFI.tw: Random Event, Fetish Interest								*/
/*  RESS.tw: Random Event, Single Slave									*/
/*  RESSTR.tw: Random Event, Single Slave (Test Realm, for debugging events)	*/
/*  RETS.tw: Random Event, Two Slaves									*/
/*  																			*/
/* Events can also be in a dedicated *.tw file, formatted as follows:						*/
/*  jeXXXXX.tw:	Justice Event													*/
/*  pXXXXXX.tw:	Player event													*/
/*  peXXXXX.tw:	Player Event focused on a slave									*/
/*  reXXXXX.tw:	Random Event													*/
/*  resXXXX.tw:	Random Event, School											*/
/*  seXXXXX.tw:	Slave Event, focuses on slaves coming or going						*/
/*  securityForceXXXXX.tw:  Security Force event										*/
/*																			*/
/* Some scenes are also stored in useGuard.tw, walkPast.tw, and toychest.tw				*/
```

I'd like to add some documentation to the head of the major event files, like RESS.  Aside from wonky tabs, does this look sensible?  Any suggested additions?

This is just based on me trying to suss out what logic has been here already, and make it more available to other newcomers.

What is the logic in the recETS name?  Recruitment Event, Two Slave?

Is there a preference at this point to add new content in standalones or RESS/etc?

**Comment by lowercase-donkey** [comment]
Is `jeSlaveDispute.tw` a typo, or is `je` a category in its own right?

**Comment by fcpmanon** [comment]
justiceEvents

**Comment by freecitiesdev** [comment]
> I'd like to add some documentation to the head of the major event files, like RESS. Aside from wonky tabs, does this look sensible? Any suggested additions?

Looks good. Add it.

> Recruitment Event, Two Slave?

Correct.

> Is there a preference at this point to add new content in standalones or RESS/etc?

No. RESS was originally designed to keep the number of passages down since the Twine IDE was having trouble with 350+ passages. Now that we're using .tw files for each passage, it's less important. Having similar events that use a lot of the same code in a single passage is good to keep bloat down by not repeating code unnecessarily, but that's it.
