### ISSUE TITLE
Can't assign certain slaves to classroom from main page, but can from classroom

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#552]
Save attached.  Sienna and Isabella cannot be assigned to the classroom from slaveSummary, but if you go to the classsroom you can assign them there.  I'm worried I broke something in slaveSummary, but is it possible that there are two different intelligence checks happening here?

[free-cities-20170529-205407.zip](https://github.com/Free-Cities/Free-Cities/files/1036994/free-cities-20170529-205407.zip)

Just built from git a second ago.

**Comment by fcpmanon** [comment]
I'm not seeing this.  Using your save with latest git, Sienna can be assigned to schoolroom from slave interact (click her name then transfer to) and Sienna also can be assigned to schoolroom by going to the facility and choosing to assign her there.  Isabella cannot be assigned by either method, as she "already has a basic education."  Consistent.

**Comment by lowercase-donkey** [comment]
Correct, but I cannot assign her to classes from the main page.  I'm not sure what to technically call the main page, but where HG is listed.

Currently, it looks like:
```
Sienna will rest. 
Improve: Rest | Confinement | Work: Fucktoy | Whore | Public Servant | House Servant | Gloryhole 

```

**Comment by fcpmanon** [comment]
Main page is fine.  That is Main.tw.  You can also call it the penthouse.

Classes is the "study in the penthouse" assignment.  It only checks for not educated and not too resistant to learn; unlike schoolroom, which also checks skill levels.

**Comment by lowercase-donkey** [comment]
Arghhh, right.   Derp.  Thanks.
