### ISSUE TITLE
Sorting coursingAssociation.tw?

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#553]
For sorting, is this an event or a location?  Where is it accessed from for a player?  I haven't managed to unlock this in the game myself yet.  

It seems to need an assigned slave like a Classroom does.

**Comment by fcpmanon** [comment]
It is a monthly Scheduled Event.  It is enabled by enacting the corresponding Coursing Policy:

> **Coursing Association**: you will sponsor a Coursing Association that will hold monthly races.

**Comment by lowercase-donkey** [comment]
Thanks.  Is this a naming inconsistency? I can tack it on to #551.  seCoursingAssociation.tw? There is already seCoursing.tw.
