### ISSUE TITLE
Can't seem to copy slave array

### ISSUE THREAD

**Issue by tc-k** [Free-Cities/Free-Cities#561]
First, this following code in newSlaveIntro.tw is bugged
```
<<elseif $activeSlave.origin == "She was recruited into your service by her sister.">>
	<<link "Use her sister as an example">>
```

That line will never get called because that recruitment event is now split into older sister, younger sister, and twin sister. So the elseif should check for those three 
<<elseif $activeSlave.origin == "She was recruited into your service by her older sister." || She was recruited into your service by her younger sister." || She was recruited into your service by her twin sister.">>

See reRelativeRecruiter.tw for the event.

However, I didn't simply submit a bugfix because there is another bug in the same section.

```
	<<replace "#introResult">>
		Your new slave appears <<if $activeSlave.devotion < -10>>reluctant to assume her new duties.<<else>>unsure what her new duties are.<</if>> You gesture towards $recruiterSister.slaveName. 
```

$recruiterSister was never defined, leading to an error when the event is called. I tried to copy the correct slave to $recruiterSister but can't seem to. The code I used is
```

<<set _i = $activeSlave.ID - 1000>>
<<set $recruiterSister = $slaves[_i]>>
```

But that didn't get me the correct slave. I instead get the very first slave in $slaves array. I think $slaves[0]. This despite _i being the correct value when I printed it. I looked at other files and it seems similar to what I did, so what did I do wrong?

Also, $recruiterMother has the same problem.

**Comment by fcpmanon** [comment]
_i is an index, ID is an ID.  An ID is not an index.  You want `<<set _sisterID = $activeSlave.ID - 1000>>` and `<<set $recruiterSister = $slaves.find(function(s) { return s.ID == _sisterID; }>>` (and then check `<<if (def $recruiterSister)>>` before using it, as $recruiterSister will be undefined if no slave exists with ID == _sisterID).

**Comment by tc-k** [comment]
Thanks.
