### ISSUE TITLE
Slave nationality is Ancient Chinese Revivalist?

### ISSUE THREAD

**Issue by Hornspare** [Free-Cities/Free-Cities#573]
I had maxed trust, maxed dev Chinese Asian, masterful slave (300 sex skills, 100 whore, 100 entertainment) running on completely maxed Chinese Revivalist Future society, and when I tried to go New Game Plus, her nationality changed to Ancient Chinese Revivalist.
Is it intentional? If so will that still count as Chinese?

**Comment by freecitiesbandit** [comment]
Paraphrasing FCDev, that's supposed to show that they're from your old arcology and hence they've been living there long enough to think of themselves as that culture as opposed to their original one.

**Comment by fcpmanon** [comment]
And yes, it will qualify them for Chinese Revivalist bonuses.
