### ISSUE TITLE
'DG SE' event slave has been gingered

### ISSUE THREAD

**Issue by Boney-M** [Free-Cities/Free-Cities#591]
The dickgirl should go pretty cheap, just ¤1500. Sounds like the owner mostly wants to not be bothered by her anymore. 

Alma is for sale and is available to inspect. She is acting twitchy and hyperactive, like she's been given a stimulant to make her seem healthier and more energetic. She may be considerably less vital than she seems. The nervous slave brokers confirm this in response to a direct question. Your intimidating reputation from your extensive combat training has its uses.

**Comment by fcpmanon** [comment]
Seems fine to me.

**Comment by Boney-M** [comment]
It can sorta make sense that maybe the guy selling her gingered her (though in that case, the plural on slave brokerS is out of place) but if it happened with the DG SE slave, it could probably also happen with events where someone's selling themselves into slavery, in which case it'd make even less sense.

**Comment by fcpmanon** [comment]
Gingering is applied by Long Slave Description if $saleDescription is set to 1.  Law Compliance is also applied by Long Slave Description if $applyLaw is set to 1.  Perhaps we should add a flag for gingering and only use it from the markets.

**Comment by fcpmanon** [comment]
This will be resolved by #684

**Comment by Boney-M** [comment]
Wow, that's a much more elegant solution than what I was considering. Nicely done.
