### ISSUE TITLE
Slaves that come to you pregnant get 'carrying their lover's child' bonus

### ISSUE THREAD

**Issue by Boney-M** [Free-Cities/Free-Cities#610]
Specifically, this bonus:

    <<if ($slaves[$i].pregSource == $slaves[$i].relationshipTarget)>>
    She can't help but feel @@.mediumaquamarine;satisfaction@@ in carrying her lover's child.
    <<set $slaves[$i].trust += 1>>

I assume because pregSource and relationshipTarget would both be 0.

**Comment by pregAnon** [comment]
I'm pretty sure that was submitted by me some time ago, and as such have handled it in my pending pull request.  It now also checks that the slave has a .relationship > 2.

**Comment by Boney-M** [comment]
Then let's consider this closed.

**Comment by Boney-M** [comment]
Actually since it isn't actually pulled in, this bug report should stay open until it is, right? Still getting the hang of communal coding.
