### ISSUE TITLE
Arcade profits aren't adding up

### ISSUE THREAD

**Issue by Boney-M** [Free-Cities/Free-Cities#616]
There are 3 inmates confined in the Arcade.
...
You were paid ¤356 for the use of Servia's holes this week. 
...
You were paid ¤328 for the use of Graccha's holes this week. 
...
You were paid ¤342 for the use of Poplicola's holes this week. 
...
The arcade makes you ¤2066 this week.

**Comment by lowercase-donkey** [comment]
Other facilities rent out "unused" slots, perhaps it's intended behavior?  You getting a cut of guest slave's take?

**Comment by Boney-M** [comment]
At the start of arcadeReport, _oldCash is set to equal $cash and _profits is set to 0. Then it runs through saWorkAGloryhole for all the slaves.

saWorkAGloryhole reports the income using ($beauty*$FResult), and increments $cash by the same amount. Neither $beauty nor $FResult change between the report and the $cash increment.

Then _oldcash is removed from $cash and is reported as the profits. The only other thing that changes $cash is the deductions for automatic surgery if the arcade is milking. So it's definitely something off somewhere instead of unused slots being rented out or similar.

The reported profits are always almost, but not quite, twice the total of the slaves' individual profits. Is it possible that saWorkAGloryhole is being run twice, once silently?

**Comment by Boney-M** [comment]
saChoosesOwnAssignment is being run alongside saWorkAGloryhole but it should smack headlong into

    <<if ($slaves[$i].choosesOwnAssignment == 0) || ($slaves[$i].fuckdoll > 0) || ($slaves[$i].fetish == "mindbroken")>>

And then have no effect.

I can't tell where the discrepancy is coming from. And I compiled the code fresh off here to test again and it's still happening.

**Comment by Boney-M** [comment]
If there's just one slave in the arcade it reports income correctly, it's only when there's multiple that there's the error.

While trying to track this down I did find an unrelated bug: #662

**Comment by Boney-M** [comment]
Well, whatever the hell was causing this, #701 fixes it.
