### ISSUE TITLE
Debt or General Finances Bug

### ISSUE THREAD

**Issue by ObstacleCorpse** [Free-Cities/Free-Cities#629]
An anon on /dgg/ has reported the following bug. I have no further context as to what led to this, but was asked to pass it along. 

![kdt8kxk](https://cloud.githubusercontent.com/assets/24576749/26741868/04c2cdb4-4790-11e7-995a-1e149b4bdd2a.jpg)

**Comment by fcpmanon** [comment]
without knowing the circumstances that led to this, we can't do much about it

**Comment by ObstacleCorpse** [comment]
Yeah, I figured there wasn't much we could do about it without context. All I have is:

```
No idea. After one turn suddenly the upkeep and current money on the screen the next turn became that.
It was after a turned in which I put 1500 bucks towards my FS, if it helps.
```
I'll add a variable display and bug report module to FC, and submit a pull request. Might make information gathering a bit easier. I'll leave this issue open if anyone wants to investigate, but feel free to close it if it's a lost cause.

**Comment by Boney-M** [comment]
Also from /dgg/, in reply to that bug being posted:

"Hey FCDev - found the math problem - it happens upon assigning a value to put into Societal Direction and hitting "back". Something must be wrong with that calculation."

**Comment by Boney-M** [comment]
Also from /dgg/:
"Okay yeah, I can confirm this happens if you make the money spent on your FS not a multiple of 1000. I set my FS spending to 1500, pressed back, and the my upkeep shot up to ridiculous levels."

**Comment by fcpmanon** [comment]
I think the code expects the user to hit Enter after typing a value into the textbox, and does not convert the entered value to a number if you press space (or the Back button).  Moving the FSSpending value-sanitizing code that currently immediately precedes the textbox line into an FSSpendingWorkaround passage and setting the nextLink from futureSocities.tw [sic] to that FSSpendingWorkaround passage, would be one way to solve this.

**Comment by fcpmanon** [comment]
It wouldn't surprise me if other uses of the `<<textbox` macro have the same problem, if anyone wants to look at how I resolved it in the pull request linked above and then spend some time checking the others.

1) Don't include a passage link in the macro if the value needs to be a number - leaving out the passage link means that hitting Enter in the box will be a no-op

2) Don't let the textbox modify the target variable directly (the variable in the " " quotes) - instead use a temporary variable and have a link somewhere on the page (or have code on the next page if there's a dedicated follow-up passage) to sanity check the entered value and then move it into the target variable
