### ISSUE TITLE
Error on surgery screen

### ISSUE THREAD

**Issue by Boney-M** [Free-Cities/Free-Cities#644]
Only happened after I removed body hair from a slave:

Error: <<if>>: assignment operator found within <<elseif>> clause (#1) (perhaps you meant to use an equality operator: ==, ===, eq, is), invalid: $activeSlave.origHColor != "bald" && $activeSlave.pubicHStyle == "bald"> $pronounCap has a normal head of hair, but is otherwise smooth and hairless. <br>&nbsp;&nbsp;&nbsp;&nbsp; [[Remove hair|Surgery Degradation][$activeSlave.origHColor = "bald",$activeSlave.hStyle = "bald",$activeSlave.hLength = 0,$cash -= $surgeryCost,$surgeryType = "hair removal"]] <<elseif $activeSlave.origHColor == "bald" && $activeSlave.pubicHStyle != "bald"> $pronounCap has a bald head, but normal hair elsewhere. <br>&nbsp;&nbsp;&nbsp;&nbsp; [[Remove body hair|Surgery Degradation][$activeSlave.pubicHStyle = "bald",$cash -= $surgeryCost,$surgeryType = "body hair removal"]] <<else

**Comment by lowercase-donkey** [comment]
Can't seem to replicate.  Any more info?

**Comment by Boney-M** [comment]
In 0.10.3.3, go to any given slave (just tested it with a starting random slave and with the first slave in cheat mode), go to remote surgery, click 'remove body hair', press continue to go back to the surgery screen, and the error should be there.

**Comment by lowercase-donkey** [comment]
Just did the same, no error. Weird.

**Comment by Boney-M** [comment]
I was using the download right off the website, it doesn't happen when I compiled the latest from here. Someone must have fixed it already.

**Comment by lowercase-donkey** [comment]
Did you look at https://github.com/Free-Cities/Free-Cities/commit/f86a453f63f40b77162ed835a520ae03be88afae?

**Comment by Boney-M** [comment]
A single missing >, because of course it was.
