### ISSUE TITLE
Rogue <</if>> in latest build

### ISSUE THREAD

**Issue by Boney-M** [Free-Cities/Free-Cities#665]
Error: child tag <</if>> was found outside of a call to its parent macro <<if>>

Trying to figure out which of the /ifs it's referring to now. It occurs on the slave summary, after se drive and instead of gender preferences, so it's almost certainly the fault of the changes I made to it.

**Comment by Boney-M** [comment]
Yep, caused by #655 

Should be fixed in #666

**Comment by Boney-M** [comment]
#670

**Comment by lowercase-donkey** [comment]
Not sure what your workflow is, but if your tools are minimal, notepad++ is pretty amazing.  Choose "HTML" from the language menu, and any "if" you highlight will show the one that corresponds.  Makes tracking these things so much faster.

You probably already have something like that though.

**Comment by Boney-M** [comment]
I'll keep that in mind for the inevitable next time I miscount my /ifs.
