### ISSUE TITLE
Help me with /if in my pull?

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#714]
Quick cry for help, something wonky going on here in my build.

https://github.com/Free-Cities/Free-Cities/pull/640/commits/4ef773e9e447484372578cbadee687418323992b

As I explain there:

"Commenting out the "Tie her up and give her a good whipping" section removes the error, but I don't see anything wrong there.

Moved a few other things into single statements while I was here to make "ifs" easier to follow.  I must be going blind."

It's a very simple section, I don't know why removing it removes the error.

**Comment by Boney-M** [comment]
This is really strange. Compiled and ran it to check that it's there and yep, definitely happening. 

Error: cannot find a closing tag for macro <<if>> 
Indicating: <<if $activeSlave.amp != 1>>

**Comment by Boney-M** [comment]
244 instances of '<<if' in the file, and 244 <</if>>. Theoretically that would indicate that there couldn't possibly be a missing <</if>>...

**Comment by pregAnon** [comment]
Line 1231, what did that removed <</if>> close?  Among your changes, that stands out the most.  Unless, of course, there are other changes not highlighted.

**Comment by Boney-M** [comment]
That /if closed the amputation check starting at line 1162. It was moved to line 1168 so it just checks for amputees for the whipping.

**Comment by pregAnon** [comment]
1167.  "<</link>"

**Comment by Boney-M** [comment]
Looks like that predates these changes. Maybe it being nested in that amputation check kept it from throwing up an error? We'll see if fixing that stops the error.

**Comment by lowercase-donkey** [comment]
Yup, it was that <</link> with the missing >.  I still have no idea why that would do what it did, but it's corrected and no longer errors.  Thanks @pregAnon !
