### ISSUE TITLE
$slaves[$i].eyes in saLongTermEffects

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#731]
Around line 3598 we see 

`<<if $slaves[$i].eyes is -2>>`

then a little later

`<<elseif $slaves[$i].eyes is -2>>`

I'm sure this is a bug, but I don't know what the eye values represent.  Eyeballs?

**Comment by Boney-M** [comment]
Looks like an .eyes value of -2 means blind. So the second one should probably be = 0 instead - it looks like it's supposed to cover what happens when slaves with normal eyes are wearing blurring glasses.

**Comment by lowercase-donkey** [comment]
Right, but that whole section is wrapped in `<<if $slaves[$i].eyes != 0>>`

**Comment by Boney-M** [comment]
I checked remoteSurgery and '.eyes == 1' is for good vision. So the latter is probably supposed to be 'elseif is 1'. Not sure what eyes == 0 would represent - no eyes at all?

**Comment by lowercase-donkey** [comment]
So:

1 == 20/20
0  == ?
-1 == Bad vision
-2 == Blind

**Comment by Boney-M** [comment]
As far as I can tell, yeah. I'll make the same change in my test fork and see if I notice it breaking anything.

**Comment by lowercase-donkey** [comment]
I wonder if 0 is implants.

**Comment by Boney-M** [comment]
At least in the cybernetics mod, that's covered by
    <<if $activeSlave.origEye == "implant">>

**Comment by lowercase-donkey** [comment]
Could zero be one eyed or injured eye?  I'm genuinely just speculating here.

The other thought would be that it's an error state that just shows it's not set.

**Comment by Boney-M** [comment]
Maybe there was originally going to be 'average eyesight' and 'good eyesight' and then FC Dev decided that was unnecessary.
