### ISSUE TITLE
Question: Second Fork for Github ?

### ISSUE THREAD

**Issue by Clegane32** [Free-Cities/Free-Cities#734]
Hi

I've no Github experience - and a quick google turned up no acceptable results. 
Github takes away a lot of the control I'm used to having. 
I'm currently using the basic windows GUI and the web client.

My goal is to have at least 3 LOCAL versions of the code
1 - *this - the master/main. For testing the current production candidate.
2 - A personal fork+branch that I upload fixes from. This should be very quick to keep updated with main (low conflicts). I will add and test fixes here before doing a "pull request"
3 - Experimental branches from the personal fork, this is to test fixes out in a very hacky way, and will also have things that might never get into the game (e.g. personal cheats)

The problem
I have these 3 set up virtually. Locally I have 2 clones, of "master" and of the "fork".
This means I have only 1 copy of each file for "2" and "3" above. When I switch branch my local files change.

In my traditional workflow I will have both "2" and "3" versions of a file open and 
[transfer a few lines over -> quick test]*10 . 

Do I need to create a new account to create a second fork ?, in order to keep 3 local copies

Thanks

**Comment by Boney-M** [comment]
When you make changes to a file in your fork, you can make a new branch instead of committing directly to the master.

**Comment by Clegane32** [comment]
Thanks for the help - I didn't know about the auto patches and was making the branches manually.

Unfortunately the auto patch branch also overwrites previous branches files.
I'll try the new acc route and see what happens

btw GITHub desktop is fucking garbage - so many errors without clean ways to fix it - rage over - hopefully

**Comment by Boney-M** [comment]
I've been using nothing but the website, haven't encountered any auto-overwrites. It's very easy to juggle multiple branches using it.

**Comment by Clegane32** [comment]
How many local copies do you have though ?

**Comment by Boney-M** [comment]
What do you mean by local? On my computer?

**Comment by Clegane32** [comment]
Ya - on my computer / harddrive

**Comment by Boney-M** [comment]
I just download the zip and compile whatever version I'm testing, I edit all the code through the website so I don't have any local versions for editing.

**Comment by Clegane32** [comment]
Ahh I see - that's the mix-up
Thanks for the help though. 

Also your beast ~10 fixes a day - 👍 👍

**Comment by Boney-M** [comment]
My secret is that half of those are my own missing /ifs

**Comment by Clegane32** [comment]
lol
