### ISSUE TITLE
Balance : Fully industrialized dairy slaves (bioReactors) produce around 1/3 to 1/4 of what they should

### ISSUE THREAD

**Issue by Clegane32** [Free-Cities/Free-Cities#743]
A 100 Dev/Tru/Health slave, with maxed out everything, with 100% Pastor + laws will generate (
Milk - Cum - femCum = Total
11688 (974) - 6027 (147) - 50(5) = 17765
9588 (799) - 6960 (174) - 50(5) = 16598
9720 (810) - 8477 (173) - 50(5) = 18247
Note 25k+ is possible for thinking slaves with milkmaids etc.)

The same slave mind broken will produce 
8820 (735) - 6120 (153) - 50(5) = 14990
6384 (532) - 3300 (75) - 50(5) = 9734
7248 (604) - 3995 (85) - 50(5) = 11293

The same slave will produce ONLY 3-4K when fully converted.

I have a change that would change that 4k to about 14.5k

The change also includes a standalone line in the weekly report with the following
12 permanently converted biological "machines" produce ¤168380 income.

**Comment by Clegane32** [comment]
The fix is e4dcba8 I can't figure a way to make a "Pull Request" with just it atm. Will work on it later

**Comment by Folant** [comment]
>I can't figure a way to make a "Pull Request" with just it atm. 

You can use `git cherry-pick e4dcba8` in GitHub Desktop.

**Comment by Clegane32** [comment]
Hi the "git cherry-pick e4dcba8" is not working as the above 2 entries show

The console automatically changed from a window console to a vim editor.... for the "git commit --allow-empty" command. I'm baffled as to why GIT is so popular.

This is my console dump - maybe I've done something retarded

------------------------
C:\Users\xxxxx\Documents\GitHub\Free-Cities2>git cherry-pick e4dcba8
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:
    git commit --allow-empty
Otherwise, please use 'git reset'
On branch master
Your branch is up-to-date with 'origin/master'.
You are currently cherry-picking commit e4dcba8.
nothing to commit, working tree clean

C:\Users\xxxxx\Documents\GitHub\Free-Cities2>git commit --allow-empty
[master 41c4f78] Bring the income of fully industrialized dairy slaves in line with the rest of the dairy (a 400% boost approximately)
 Date: Sun Jun 11 17:04:44 2017 +0100

C:\Users\xxxxx\Documents\GitHub\Free-Cities2>git remote add upsteam https://github.com/Free-Cities/Free-Cities.git

C:\Users\xxxxx\Documents\GitHub\Free-Cities2>git remote -v
origin  https://github.com/Clegane32/Free-Cities.git (fetch)
origin  https://github.com/Clegane32/Free-Cities.git (push)
upsteam https://github.com/Free-Cities/Free-Cities.git (fetch)
upsteam https://github.com/Free-Cities/Free-Cities.git (push)

C:\Users\xxxxx\Documents\GitHub\Free-Cities2>git cherry-pick e4dcba8
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:
    git commit --allow-empty
Otherwise, please use 'git reset'
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
You are currently cherry-picking commit e4dcba8.
nothing to commit, working tree clean

C:\Users\xxxxx\Documents\GitHub\Free-Cities2>git fetch --all
Fetching origin
Fetching upsteam
From https://github.com/Free-Cities/Free-Cities
 * [new branch]      master     -> upsteam/master
 * [new branch]      revert-420-ra-merge-rules -> upsteam/revert-420-ra-merge-rules

C:\Users\xxxxx\Documents\GitHub\Free-Cities2>git cherry-pick e4dcba8
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:
    git commit --allow-empty
Otherwise, please use 'git reset'
On branch master
Your branch is up-to-date with 'origin/master'.
You are currently cherry-picking commit e4dcba8.
nothing to commit, working tree clean

C:\Users\xxxxx\Documents\GitHub\Free-Cities2>git commit --allow-empty
[master 3dcc150] Bring the income of fully industrialized dairy slaves in line with the rest of the dairy (a 400% boost approximately)
 Date: Sun Jun 11 17:04:44 2017 +0100

**Comment by Folant** [comment]
My best guess this is due to Clegane32/master is ahead of Free-Cities/master by 3(5 now?) commits, and you're trying to cherry pick commit to the Clegane32/master branch again. 
This is working for me, however, if I set your repo as upstream: 
````git checkout -b dairyfix````
````git reset --soft HEAD~5````
discard all files except dairyReport.tw
````git fetch upstream````
````git merge upstream/master````
````git commit -m "Bring the income of fully industrialized dairy slaves in line with the rest of the dairy (a 400% boost approximately"````

**Comment by Clegane32** [comment]
Thank you Folant. 

That worked. I used a "git stash" to remove one error and did the commit via the UI, but finally the pull request worked

GIT..... I've put off learning it for years, maybe I should have waited a few more 😕
