### ISSUE TITLE
Vector Art: Issues with Clothing

### ISSUE THREAD

**Issue by prndev** [Free-Cities/Free-Cities#766]
### General
Most clothing options do not perfectly match the textual description (eg. placement of rings in "straps" outfit, cutouts in latex outfit). This is often due to technical reasons. Issues like these should be considered "artistic freedom".
### Known Issues with Specific Kinds of Clothing
* straps  
The "uncomfortable straps" outfit is partly hidden by boobs on flat chested slaves. This is partly my fault. My extensions do not exempt boobs of size 0 to be displayed at all. Pregnant bellies are not regarded either.
* latex  
Art display does not differentiate between "fuckdoll / full body latex", "uncomfortable latex" and "nice latex catsuit".
### Future Work
I open this issue so people know I am aware of the problems. I hope to get in touch with the original vector art artist to learn how much I can change the code and art without interfering with his workflow.

**Comment by freecitiesbandit** [comment]
Any thoughts on the new addition to the salon added by lowercase-donkey, such as the addition of dyed skin and hair highlights?

**Comment by lowercase-donkey** [comment]
If you see this @prndev I'd love if you could take a look at #843 as well.  Cheers!

**Comment by prndev** [comment]
Regarding dyed skin and highlights: Currently, the skin colour is "hardcoded" in sets of independent files. In my opinion, it would be wise to assign all skin of one slave to a single CSS class and colour that. I am unsure about performance, though. And it would not work with Internet Explorer. There is a decision to be made of what we would like to have.

**Comment by freecitiesbandit** [comment]
I can't seem to find a source for this anymore, but I recall the original vector artist provided the art 'as is' and without intention of adding to it. Could be misremembering it for the rendered image set though.

**Comment by Nov-X** [comment]
Originial svg maker here. What's the issue.

**Comment by prndev** [comment]
@Nov-X Glad to hear from you. :)

* It seems, some assets were missing in "vector source.svg": I could not find the chastity cages or the pubic hair. I took the liberty of taking the existing ones from the art set and combined them into the svg.
* While examining the SVG, I noticed inconsistent naming of layers (e.g. boob_3_ in boob_0). I homogenised them.
* #843 is bothered by the unused space left and right. I cropped the source canvas.
* No one without Illustrator can export the layers into separate files. I wrote a script to do this.

As of today, these changes were made solely in my experimental [branch](/prndev/Free-Cities/tree/embedded_vector_art_experiments). I can see you are working with Illustrator. I want to make sure my changes do not break your workflow before merging it into the upstream master branch.

**Comment by Nov-X** [comment]
As I'm not very actively making any additions, you don't need to worry about breaking workflows. I did create the source svg using illustrator, and I'm currently just playing around with making facial features. When I get something workable, I'm thinking it's probably better to just provide the files and let others better at it implement them.

**Comment by prndev** [comment]
That's great news. Thank you.

**Comment by freecitiesdev** [comment]
This is closed for now per #923, which makes enough changes to the vector art display that existing issues are no longer relevant.
