### ISSUE TITLE
New slave anal fears

### ISSUE THREAD

**Issue by eldestdawn** [Free-Cities/Free-Cities#799]
When going through the enslavement process, after accepting a slave but before choosing what to do with them it says they fear for their virgin anus even though some of them are NOT anal virgins.

This also happened after sending a criminal to the stocks as punishment. They were a virgin before the stocks but afterwards they weren't so them fearing for their (no longer) virgin anus is just not right.

This happens at random events as well as after purchasing slaves through the market. Not all slaves fear for the ass though, and I'm unable to pin-point why.

**Comment by kopareigns** [comment]
Do you happen to be running gender radicalism? If so I think I've fixed it in #796

**Comment by eldestdawn** [comment]
I'll need to double check but I think I've seen it before I got Gender Radicalism. I'll have to make a new game though so it may take a while. I usually pick a new city that has paternalism for starting so if I come across it before I take another society, then I'll know it's not just GR society model that's the problem.

**Comment by eldestdawn** [comment]
Tried multiple things, it only shows up with Gender Radicalism society model so closing ticket.
