### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by buttwhy** [Free-Cities/Free-Cities#801]
ERROR: AS Dump, activeSlave invalid, returnTo is 'Main', previous passage was 'Matchmaking'. Please report this.

------

Happened when I tried to talk to an Emotional Slut slave about Relationships. The next screen asked me to pick another Worshipful Emotional Slut to pair her with, but I didn't have one. When I clicked on Continue, this error message came up.

**Comment by pregAnon** [comment]
$activeSlave never gets set if you back out without selecting an option.  My pending merge request corrects this, or at least satisfies asDump.

**Comment by eldestdawn** [comment]
Error also happens when you try to marry a slave after enabling it through policies.

**Comment by freecitiesdev** [comment]
Unable to replicate; I think this one is fixed.
