### ISSUE TITLE
Suggestion: The addition of French.

### ISSUE THREAD

**Issue by serveral1** [Free-Cities/Free-Cities#821]
First and foremost: I'm not French. I don't even speak French to begin with, so don't take this as an issue of pride.

I'm willing to bet this has been suggested before (probably as part of adding more languages) so excuse me if I'm touching a previously discussed topic that hasn't been able to move forward due to engine constrains or something else. 

However, as this game deals with a "believable" futuristic setting I think the addition of French as a lingua franca should taken into consideration, as it's not only a language currently spoken all around the world (it's pretty much regarded as the language of diplomacy), but it's also predicted to grow even further in the near future (more specifically in Africa).

Also I believe the addition of other lingua francas, that are part of current and perhaps future revivalism models, should also be taken into consideration (like Japanese for Edo revivalism and maybe even Latin for it's Roman counterpart), albeit they'd have some sort of restriction and could only made lingua francas of arcologies following those paths.

**Comment by Boney-M** [comment]
You can enter any language into the custom field when you create a game, and the Revivalist FSs already penalize you if you don't change to their language and there's a button to do so on the arcology options screen.

**Comment by serveral1** [comment]
Wow... I actually never noticed that.

I guess this was just a bad case of tunnel vision.
