### ISSUE TITLE
Help: working on piercing/tattoo descriptions

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#832]
Widgets are a really great way to have descriptions and edits apply everywhere, obviously.  I just made #831 where I am able to use a few widgets for piercings.  The problem:

The widgets are built:
`<<widget "boobs">>`
`1: Boob desciption`
`<<if piercing>>`
  `         2:  Piercing description`
`<</if>>`
`<</widget>>`

So I can't really call all the nested descriptions of naval rings or earings without grabbing a ton of stuff about the body part.

So first question: Can I nest widgets explicitly?  Can I break out piercings from `<<BellyDescription>>` into a new widget, and then have`<<BellyDescription>>` call `<<BellyPiercingDescription>>`?  So:

`<<widget "boobs">>`
`1: Body part`
`<<if piercing>>`
  `         <<boobPiercings>>`
`<</if>>`
`<</widget>>`

`<<widget "boobPiercings">>`
`<<if piercing>>`
 `2:  Piercing descrption`
`<</if>>`
`<</widget>>`

That way, the rest of the code base can still just call `<<boobs>>` without needing to call  `<<boobPiercings>` explicitly, too.

**Comment by pregAnon** [comment]
You can.  I did it with hairstyles.

**Comment by lowercase-donkey** [comment]
Oh nice!  Not only that but you can fire it before it's defined.  Heck yeah, thanks!
