### ISSUE TITLE
resstr bug?

### ISSUE THREAD

**Issue by 000-250-006** [Free-Cities/Free-Cities#84]
I was running through the latest version and had this pop up during weekly reports

> Punish her
<click "Threaten her with the industrial Dairy">> Error: <<replace>>: no elements matched the selector "#name" Error: <<replace>>: no elements matched the selector "#result" Error: child tag <</click>> was found outside of a call to its parent macro <<click>>
Threaten to convert her into a Fuckdoll
Comfort her 

It was generated from resstr.tw line 95, case "im scared", but I don't know enough about the internals yet to be able to figure what fell over. Figured I'd post a bug anyways in case you do :P

**Comment by FCBourbonDrinker** [comment]
It looks like this line:
<br><click "Threaten her with the industrial Dairy">>

should be:
<br><<click "Threaten her with the industrial Dairy">>

It's missing the opening < from the statement following the BR

**Comment by 000-250-006** [comment]
Yeah, I wondered about that, but the paste is from the generated code. I'm not sure where the function it calls resides in the tree so I didn't have a chance to see if it was the problem or it just came up like that when it triggered the error.

Side suggestion for debug/cheat mode: Have it list the type of event triggered, not just which events file it'll call? It'd make it easier to figure which one to use to replicate this type of thing.

**Comment by 000-250-006** [comment]
OK, went digging, you were right

resstr.tw line 299

> &lt;br&gt;<click "Threaten her with the industrial Dairy">>

You want to make a change and make the pull req? You figured it, after all.

**Comment by FCBourbonDrinker** [comment]
Go ahead.  I'm juggling several things at the moment, so may not get back to this anytime soon.

**Comment by 000-250-006** [comment]
Done

#86 

Apologies to @freecitiesdev for the messy pull req, still figuring out git too :P
