### ISSUE TITLE
Suggestion: Head Girl Priorities

### ISSUE THREAD

**Issue by buttwhy** [Free-Cities/Free-Cities#841]
After clarifying the intended behavior of the Head Girl, I feel that her activities should be based on her assigned tasks over every available slave, instead of based on the first girl (ordered by the $slaves array) to match one of her assigned tasks. 

For example, right now, if you have two available slaves, Alice and Beth, where Alice is unskilled, and Beth has a flaw you want fixed, your HG might (depending on how your slaves are sorted) train Alice to raise her skills instead of fixing Beth's flaws.

What I suggest is that your HG would prioritize fixing Beth's flaws before raising Alice's skills, regardless of how the slaves are sorted.

**Comment by kopareigns** [comment]
Should be implemented by my pending pull request #849
