### ISSUE TITLE
Vector art: dead zone

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#843]
I'm trying to display vector art in a few new places (#842), and it's exposing what I hope is a fixable bug.

Try to choose options that are displayed close to the the art, and you can't. The art is clearly "bigger" than it needs to be, or else is projecting some kind of death field that eats mouse clicks.

As a workaround, I've added an option at the bottom of the screen to hide the art temporarily with /replace.

Thoughts?

**Comment by prndev** [comment]
I noticed this, too. I have some days off in August. Then, I might be able to explore this issue thoroughly.

**Comment by prndev** [comment]
My work resulted in an avalanche of ideas of how to improve the vector art display. I devised a method of questionable approach to embed the vector art directly into twine passages. Downloading the image pack is no longer necessary. However, the source gets quite bloated. It is debatable whether we would want this.

The major upside is the slaves skin or hair (or anything, really) ability to be given an arbitrary colour. This way, the colour variations do not need to be maintained in separate files. This is ideal for the new dye function introduced in 7b8c15b.

@lowercase-donkey, would you please look into my [branch](/prndev/Free-Cities/tree/embedded_vector_art_experiments) and tell me whether this is something you can use? Only vagina, boob and penis size is varied at the moment. Everything else is strictly static. And blue.

**Comment by lowercase-donkey** [comment]
I'm taking a look now.  Seems pretty cool!

The margin still seems to be a problem, not sure if you wanted me to check that.

> The major upside is the slaves skin or hair (or anything, really) ability to be given an arbitrary colour. This way, the colour variations do not need to be maintained in separate files. This is ideal for the new dye function 

This has me pretty excited.  Would this also reduce download size by moving color tinting client side?

**Comment by prndev** [comment]
> This has me pretty excited.

Thank you. That was one of my goals. See `src/art/vector/Set_Colour_Hair.tw` in prndev/Free-Cities@fde2cb0 for an example of how what is possible.

> The margin still seems to be a problem (...)

That is weird. It works for me in Chrome and Firefox. In the Wardrobe, the Slave Description and the Main Menu Slave List. This screenshot shows the highlighted vector art margin:
![vector_art_margins](https://user-images.githubusercontent.com/25567918/28325115-57cf22fc-6bdd-11e7-9664-6144d495dc7c.png) Any idea of what I might do different from you? Please checkout my [branch](/prndev/Free-Cities/tree/embedded_vector_art_experiments) again. I might have fixed this issue without even realizing it was there.

> Would this also reduce download size by moving color tinting client side?

Yes. The download size would be reduced as in "no longer one file per color variation". However, the art is no longer separated from the game. Instead, it is compiled right into the `FC.html`.

**Comment by freecitiesbandit** [comment]
@freecitiesdev This seems like a discussion you might want to be aware of.

**Comment by lowercase-donkey** [comment]
Dead zone seems fixed in your build; I only tested Chrome.

If this is finally fixed, you can go ahead and nip the "toggle art just for now" code if you want.  It was just a workaround.

Code appears in wardrobeUse, bodyMod, remoteSurgery, and salon (so, the four rooms for slave interact.)

**Comment by freecitiesdev** [comment]
This is extremely impressive. It seems to be loading significantly faster, for one thing. I'm not really seeing a downside, here, so I'd like to see this in a pull request as soon as all the parts are working.

That said, I'm not really sure what I'm looking at, here. I take it the .tw files with numeric paths are defining the vectors for the art? How are you getting these values?

**Comment by prndev** [comment]
>  I take it the .tw files with numeric paths are defining the vectors for the art?

Yes, indeed.

> How are you getting these values?

In response to your question, I wrote down an elaborate answer in the [README](/prndev/Free-Cities/tree/embedded_vector_art_experiments/artTools#4-split-the-layers). I presume, section "split the layers" is the most interesting part. Basically, I wrote a set of scripts to handle the vector data (SVG is XML, so it is somewhat human readable).

**Comment by freecitiesdev** [comment]
That's what I thought. So here's what that makes me wonder. As I'm sure you've noticed, the different boob sizes for example are just resizes of a single base image. Rather than having seven .svgs turned into vector data by a script, would it be possible to have a single .svg that the script scales into 7+ options? That would save some space and clutter, or alternatively provide more options.

**Comment by lowercase-donkey** [comment]
>Rather than having seven .svgs turned into vector data by a script, would it be possible to have a single .svg that the script scales into 7+ options? 

If this is possible, tattoo and brand overlays start to become sane possibilities...

**Comment by prndev** [comment]
Let's carry on this discussion in a more general issue #889 and keep this issue focused on the original topic (then we can close it someday).

**Comment by prndev** [comment]
I completed my work on porting the existing art (except for my own straps and ropes) over to the embedded implementation. It works alright with the games I use for play-testing. If you could spare some time, please try [my experimental branch](/prndev/Free-Cities/tree/embedded_vector_art_experiments). If neither of us can find any serious problems with it within the next days, I want to create a pull request.
