### ISSUE TITLE
Pit fight from another universe

### ISSUE THREAD

**Issue by 000-250-006** [Free-Cities/Free-Cities#87]
> Pleasant realizes that Ruby's wingspan gives her a huge reach advantage

OK, spill - where's the winged bodymods mod??? :)

**Comment by Folant** [comment]
https://en.wikipedia.org/wiki/Arm_span
Arm span or reach (sometimes referred to as _wingspan_)
Seems legit.

**Comment by 000-250-006** [comment]
*sobs as visions of harpy slaves go flying out the window*
