### ISSUE TITLE
Could vectors respect $showBodyMods?

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#887]
I don't even know if it's possible, but I just went through a lot of missing checks for that in longSlaveDesc.  Then I glanced over at the vector, and there were the mods!  So I thought I'd ask.

**Comment by lowercase-donkey** [comment]
Changed phrasing to be less rude.  Come on, donkey.

**Comment by prndev** [comment]
Yes, I'm on it.
