### ISSUE TITLE
What happened to bellyTat, and why is vaginaTat really bellyTat.

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#888]
Copying a comment I posted on a recent comit:

 Why are vagina tats and abdomen/pubis tats confused? The vaginaTat really is just abdomen tats, albeit ones that sometimes refer to the vagina.

We even have this segment:
```
$possessiveCap abdomen is tattooed with tribal patterns that draw the eye down toward $possessive <<if $activeSlave.dick != 0>>cock<<elseif $activeSlave.vagina == -1>>featureless crotch<<else>>vagina<</if>>.
```

How the heck is that a 'vagina' tattoo?

``Her abdomen is tattooed in a Holstein cow pattern.`` Here there's no reference to vaginas at all.

To avoid breaking a lot of slaves, would it be fine to leave the variable name in code, add a coded labiaTat, and change the displayed slot from Vagina to Abdomen? That way, players think they are tattooing the abdomen, but it's still saving it to the same vaginaTat variable. Then, they can also tat labia/clit the way they tat a dick.

Also, what happened to bellyTat?  I see it twice in `git grep`, both in longslave.  Clearly, it doesn't do anything.  But it did, once.

**Comment by prndev** [comment]
I noticed that, too. I suggest cleaning it up.

On a similar matter: It seems that "education" is represented by an `intelligenceImplant` which scales from 0.0 to 1.0. Whereas most other variables scale from 0 to 100.

In my opinion, it would be wise to do a global replace/rename (refactor). It will break all existing save games, but it makes the code more maintainable. From my experience, that is what counts in the long run.

**Comment by pregAnon** [comment]
.bellyTat can be safely removed, it likely hitched a ride with other nearby content during one of fcpmanon's mass updates.  As for variable renaming, why bother?  Is it really worth breaking all saves for something only those interested in digging into the code will see?

**Comment by lowercase-donkey** [comment]
@pregAnon I guess it depends how you look at it.  Maybe I went too far saying break.  Basically, if it's changed, anyone with a slave who had/has a vaginaTat is going to see a new description for it.  If they want the old description, they'd have to scrub it and give them an actual abdomen tattoo.  We could use the old bellyTat tag for that.  I think reddit has a point, bellies are a big patch of skin and it's weird we can brand them but not explicitly tattoo them.

Alternately, as I think you're implying, we can leave vaginaTat as is with it's descriptions, but going forward refer to this tattoo slot as Belly on the front end.  Then, add labiaTat for the new dick parallel.

I can see going either way.

**Comment by pregAnon** [comment]
I was more referring to changing .intelligenceImplant, but .vaginaTat more or less refers to the area from the pubic mound up through the lower belly. The area between is shared between it, and .boobsTat in some cases.  Especially when they are small; when they are large, good luck seeing anything anyway.

**Comment by pregAnon** [comment]
As for .bellyTat, it is a specialized navel tattoo.  It is currently held back by the biggest description conflict you'll ever see.  I'm taking steps to remedy it, but it will take a lot of time to deal with.  In the meantime, please stop disturbing "BellyDescription", you are agitating the conflict.

**Comment by lowercase-donkey** [comment]
I largely agree.

>The area between is shared between it, and .boobsTat in some cases. Especially when they are small; when they are large, good luck seeing anything anyway.

Still seems to be cheating to have dicks as their own slot and no real vagina options.  We can tattoo the anus, for example, which is a much smaller hole, as well as buttocks.

**Comment by pregAnon** [comment]
I can't really picture a vaginal tattoo, honestly.  But creating a new variable just for it would be the way to go to avoid greater conflicts.

**Comment by freecitiesbandit** [comment]
@lowercase-donkey I think I'm in agreement with pregAnon. You mention being able to tattoo the anus, but to be honest that's the hardest tattoo description to come up with anything interesting for. You end up having something like "<image> is tattooed around her anus" or "a ring of <text> is tattooed around her anus". Thinking of something different to then tattoo on/around the vagina would be difficult. 

In addition, I think the most interesting vaginal/abdominal tattoos end up being tramp stamps above the vagina, rather than vaginal tattoos in themselves. If a tattoo set has a really good idea for something to put on the vagina, it'd better to be the exception rather than the norm.

**Comment by lowercase-donkey** [comment]
Makes sense to me.  Thanks, all.
