### ISSUE TITLE
src/config/start.tw keeps on getting (re)committed

### ISSUE THREAD

**Issue by dorkulon** [Free-Cities/Free-Cities#90]
Especially with the divergence of compile and compile.bat, src/config/start.tw keeps on getting loads of churn; sometimes it's committed with / as the path separator and with relative paths, sometimes with full paths and with \ as the path separator. Regardless, it should always be regenerated from scratch, and therefore not be in the repository (except as an entry in .gitignore).

I'd previously committed a change to remove start.tw entirely, but that got reverted; hence, I'm opening this issue to avoid this from recurring.

**Comment by freecitiesdev** [comment]
I wondered why it kept getting recommitted. I don't know why it was removed from .gitignore, though it's entirely possible I fumbled that in due to git newness. Did anyone remove it from .gitignore intentionally?

**Comment by FCBourbonDrinker** [comment]
Nope.  I hadn't really noticed it before, but then I saw that it contained someone's full working directory path so I attempted to clean it up (assuming it was needed).  Now that I know its not needed, I'll make sure to not re-commit it.

**Comment by Bane70** [comment]
Can it be added to .gitignore or something?

**Comment by Folant** [comment]
The problem is that tracked files can't be added to .gitignore directly. 
```git rm -r --cache src/config/start.tw && echo src/config/start.tw > .gitignore``` however should do the trick
