### ISSUE TITLE
Looking for a recent change.

### ISSUE THREAD

**Issue by Weresmilodon** [Free-Cities/Free-Cities#916]
Ok, someone recently made a little change to hormones, and i've been trying to track down the exact commit for a while now. I should have been in bed three hours ago, so i'm giving up for now.

The change is such (if i remember correctly): When hormones will no longer cause any changes, the slave is taken off them.
What i was planning to look for: If this also affects the RA, or if everyone taken off hormones will immidietly be but back on them again.

Does this sound familiar to anyone?

**Comment by Folant** [comment]
https://github.com/Free-Cities/Free-Cities/commit/473add1dc538535796a9725eb561fb19236c386e#diff-bc3e7db543de21d2b1f4bd2007811c3b
````
<<if _Effects.length < 1>>
	$possessiveCap body has fully adapted to its hormones.
	<<if $slaves[$i].drugs == "hormone enhancers">>
		<<set $slaves[$i].drugs = "none">>
	<</if>>
````
?

**Comment by Weresmilodon** [comment]
Looks familiar, but i think the length was 10, and there was an extra line before or after that <</if>>.

Can't swear on it though. All this is doing is removing the hormone enhancers, not hormones themselves.

I'm starting to think the change was removed, because i can't find it.
