### ISSUE TITLE
Age of facelift: 26 seems very young?

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#922]
As currently written, facelifts become available for slaves older than 25.  It's a minor thing, but shouldn't we hold this for a little later?  I mean, they only start working at 18.  Quick google searches suggest people really start getting them in their 50s at earliest, although slaves retire at 45 and work hard.  Maybe open it at 35-40?  

I'm not clear on what `ageImplant` does mechanically though.

Edit: after looking again in code, I believe all `ageImplant` does is improve beauty checks:

`($args[0].age*3) + (5*$args[0].ageImplant)`

From a certain point of view, it's great to make numbers go up for all slaves.  On the other hand, I think there's value in saving this as a choice for later, when economist players are weighing putting money into an older slave vs anticipated return.

**Comment by Clegane32** [comment]
Megan Fox (who had maxed out facial beauty scores) had a lot of surgery somewhere in her mid 20's. 
While it might not have been technically a face lift, it seems it was certainly an attempt to fight ageing.

Ageing is very brutal to attractiveness in FC (as it should be), it makes sense a LOT of effort would be put into minimizing the visibility of age to customers/clients.

IMO ageImplant does a decent job at this. And I think starting at 25 makes a lot of sense.

**Comment by lowercase-donkey** [comment]
I partly see your point, but maybe you didn't see mine.  I'm not saying they shouldn't be able to have facial surgery.  Obviously younger people have cosmetic surgery, and that's available here too:

`Make conventionally feminine | Cute | Exotic | Androgynous | Just improve attractiveness`

I'm specifically talking about surgery that's reversing the effects of aging.  Are people really seeing wrinkly saggy faces at 26?

Megan Fox was getting surgery in pursuit of an ideal of beauty.  Megan Fox was also aging (one day at a time.)  I don't think that meant she had a wrinkly drooping face in her twenties, although it's possible.  Instead, I think she was stabbing that `Just improve attractiveness` button.

**Comment by freecitiesdev** [comment]
I think the current system is the least-worst solution as long as there's a once-only, 0 or 1 surgery to apply. There's definitely room here for more content, though. Unless you want it, I can take this one. I'm thinking about making .faceImplant track how artificial the slave's face looks, with each of a variety of facial surgeries incrementing it by one. .faceImplant would then cause increasing beauty penalties above a certain threshold, with Purism and Transformationism lowering and raising that threshold respectively.

**Comment by lowercase-donkey** [comment]
I think, if you have time, that would be ideal.  Having an anti-aging surgery as a one-and-done doesn't make much real world sense.  Taking content off the table makes surgery lovers unhappy.

Integrating it with Purism and Transformationism is a great idea.  Consider Maturity/Youth Preferentialism as well.

The only drawnback I can see is this makes it "just another surgery" that's very easy to spam click for slaves.  Gameplay loses out a bit, I think, because beauty is always "only a number" and when everyone gets +X from aging surgery, no-one does, and now there's no way to make older slaves competitive.

However, certainly willing to give that up.

**Comment by freecitiesdev** [comment]
Addressed by #939. Closing.
