### ISSUE TITLE
Peacekeeper error:

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#926]
> On the other hand, General Clark has been successful in these difficult times in no small part due to his willingness to bend the rules. If he sees an opportunity to work with an ambitious arcology owner in furtherance of his goals, he'll probably take it. 

`Error: <<for>>: bad conditional expression: Cannot read property 'length' of undefined`

First encounter, choose to agree to share intelligence.
[free-cities-20170804-004841.zip](https://github.com/Free-Cities/Free-Cities/files/1199254/free-cities-20170804-004841.zip)

@freecitiesdev any thoughts?  I can't figure it out.  Is it just that the local variable isn't initialized?

**Comment by Folant** [comment]
https://github.com/Free-Cities/Free-Cities/blob/71f808dd65f9f2320ce21350faf931272ed28899/src/uncategorized/pPeacekeepersIntro.tw#L59-L62
I have no idea why we need this loop here at all.
````
<<for $i = 0; $i < _newSlaves.length; $i++>>
		....
<</for>>
````

**Comment by freecitiesdev** [comment]
>I have no idea why we need this loop here at all.

And neither do I. That's... special, even for me.

**Comment by Folant** [comment]
Can be closed after https://github.com/Free-Cities/Free-Cities/commit/a646de1076f0591a4db177fc21e8b136ac6a2389 🤔
