### ISSUE TITLE
New "compile_debug" can't handle directories with whitespace

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#930]
The "update" breaks the script completely for me, producing the error that a directory is not recognized as an internal command, etc.

However, the directory has whitespace in it. So if the folder is "D:\Git\My Free Cities" then it would be showing "'D:\Git\My' is not recognized as command."

I know this reduces redundancy, but it seems to increase complexity.  Old script works fine.  5d05d2db557c88fd6d4c1f00a9b5b67cce844bec is where this started.  @prndev can you check it out?

**Comment by prndev** [comment]
Uh, dang! I forgot the quotes. I am so sorry.

**Comment by freecitiesdev** [comment]
I believe this is corrected; closing. Let me know if it's not.

**Comment by lowercase-donkey** [comment]
Yes, works fine for me.
