### ISSUE TITLE
Missing option to remove vagina.

### ISSUE THREAD

**Issue by WarlordMLP** [Free-Cities/Free-Cities#978]
You can't remove a strictly female slaves vagina.

The following needs to be added to the remote surgery tw.

<<if ($activeSlave.vagina > -1)>>
	<<if $activeSlave.indentureRestrictions < 1>>
	<br>&nbsp;&nbsp;&nbsp;&nbsp;
	It's possible to remove $possessive pussy..
	[[Remove pussy|Surgery Degradation][$activeSlave.vagina = -1,$activeSlave.ovaries = 0,$activeSlave.preg = -2,$activeSlave.pregSource = 0,$activeSlave.vaginalSkill = 0,$cash -= $surgeryCost,$activeSlave.health -= 20,$surgeryType = "vaginaRemoval"]] <<if $activeSlave.ovaries == 1>>//This will remove $possessive ovaries as well//<</if>>
	<</if>>
<</if>>

If I could figure out how to use github I would do it myself.

**Comment by lowercase-donkey** [comment]
I thought I fixed that...

Thanks though!  I'll check it out.

**Comment by WarlordMLP** [comment]
That's what I meant was about the girls with vag only was unremoveable in version i'm playing which was before N Family. I called myself looking at the github Tw file and that it still couldn't be done. Thx for fix though, regardless of when you did it. :)

**Comment by lowercase-donkey** [comment]
No problem!  You can close this then.
