### ISSUE TITLE
$rep issue

### ISSUE THREAD

**Issue by eldestdawn** [Free-Cities/Free-Cities#981]
I keep getting a reputation value of ($rep) whenever i get to the financial report page for the weekly report. attached is a save before getting there, just continue and check the page for WHY it is giving the bad value because i don't know where to look.

[free-cities-20170817-231549.zip](https://github.com/Free-Cities/Free-Cities/files/1233476/free-cities-20170817-231549.zip)

**Comment by Folant** [comment]
There's something wrong with Paternalist FS ( `$arcologies[0].FSPaternalist` is being set to `NaN` somehow). You can abandon it for now and reset the rep through options until it's fixed.

**Comment by eldestdawn** [comment]
Rep resets when you refresh the page too (F5 or refresh button on the browser), just not on the financial report page.

Come to think of it, this all started when I found out who my rival was after the daughters of liberty attacked my archology. maybe that is why it is being set as the wrong value? The war is already over in that save though so don't know if it is something that can be reset to check or not. Also, the archology started with paternalism so should look into that as well.

**Comment by eldestdawn** [comment]
bleh wrong button clicked when commenting.

**Comment by Folant** [comment]
Should be good now.
