### ISSUE TITLE
Can't assign slaves to the clinic

### ISSUE THREAD

**Issue by keramond** [Free-Cities/Free-Cities#990]
in latest compiled version (short before post) you can not assign slaves to the clinic. i think clinicSlaves assignment does something wrong, because the rules which attempt to assign to clinic also throw errors on application.

**Comment by keramond** [comment]
yeah, that did it, thank you for your fast fix :)

**Comment by Frodfurgurn1991** [comment]
I was the one that introduced the bug in the first place :sweat_smile:
