### ISSUE TITLE
shelter slave inspection.

### ISSUE THREAD

**Issue by WarlordMLP** [Free-Cities/Free-Cities#994]
the inspection for the mindbroken slave is bugged, because the slaves background does not match the one in the shelter inspection event. It's missing the part about (**you bought this slave at the slave shelter.**) It's an easy fix, if I could work the blasted github I do it myself.

**Comment by kopareigns** [comment]
Are you sure this is still a problem? I'm pretty sure I fixed this [here](https://github.com/Free-Cities/Free-Cities/commit/a39c3f0f2b12ea7a29e6a2fb99a4c19dbae5b4d3#diff-5b144791ea3bd8f383535a2afead60d9).
