### ISSUE TITLE
Peacekeepers event Error

### ISSUE THREAD

**Issue by buttwhy** [Free-Cities/Free-Cities#995]
During the Peacekeepers event when the General asks you fund him to help him start a new country, an error shows up: 

Error: <<if>>: bad conditional expression in <<if>> clause: illegal character

and the mouseover text for the error is:

<<if $cash >= ¤250000>>

**Comment by Folant** [comment]
It's fixed in https://github.com/Free-Cities/Free-Cities/commit/98ae4e384bb72b7fa011f36fe16c1d8b86d5ad89#diff-4d6d88b178dab70c50723a36bfb6f22d
